name = "ParsePair"

[[input]]
name = "input"
type = "String"

[[input]]
name = "separator"
type = "String"

[[output]]
type = "Value" # because we don't have support for unstructuring Map yet... would be a Map of Numbers