flow = "arg-print"
docs = "DESCRIPTION.md"

[[process]]
source = "lib://context/args/get"

[[process]]
source = "lib://context/stdio/stdout"

[[connection]]
name = "print-flow-name"
from = "get/json/2"
to = "stdout"