flow = "primitives"

# 1 plus 2 = 3
[[process]]
alias = "add"
source = "lib://flowstdlib/math/add"
input.i1 = {Once =  2}
input.i2 = {Once =  1}

# 3 / 2 = 1.5
[[process]]
alias = "divide"
source = "lib://flowstdlib/math/divide"
input.divisor = {Once =  2}

[[connection]]
from = "add/sum"
to = "divide/dividend"

[[connection]]
from = "divide/result"
to = "print"

[[process]]
alias = "tap"
source = "lib://flowstdlib/control/tap"
input.control = {Once =  false}

#compare result (1.5) to 1
[[process]]
alias = "compare"
source = "lib://flowstdlib/math/compare"
input.right = {Once =  1}

[[connection]]
from = "divide/result"
to = "tap/data"

[[connection]]
from = "divide/result"
to = "compare/left"

[[connection]]
from = "compare/gt"
to = "print"

[[process]]
alias = "print"
source = "lib://flowruntime/stdio/stdout"

[[connection]]
from = "tap"
to = "print"