flow = "primitives"

[[process]]
alias = "sum"
source = "lib://flowstdlib/math/add.toml"
input.i1 = {once = 1}
input.i2 = {once = 1}

[[process]]
alias = "add_again"
source = "lib://flowstdlib/math/add.toml"
input.i2 = {once = 1}

[[connection]]
from = "process/sum"
to = "process/add_again/i1"

[[process]]
alias = "to_string"
source = "lib://flowstdlib/fmt/to_string.toml"

[[connection]]
from = "process/add_again"
to = "process/to_string"

[[process]]
alias = "tap"
source = "lib://flowstdlib/control/tap.toml"
input.control = {once = false}

[[process]]
alias = "compare"
source = "lib://flowstdlib/control/compare.toml"
input.right = {once = 2}

[[connection]]
from = "process/add_again"
to = "process/tap/data"

[[connection]]
from = "process/add_again"
to = "process/compare/left"

[[connection]]
from = "process/compare/gt"
to = "process/to_string"

[[process]]
alias = "print"
source = "lib://flowr/stdio/stdout.toml"

[[connection]]
from = "process/tap"
to = "process/to_string"

[[connection]]
from = "process/to_string"
to = "process/print"