flow = "primitives"

[[value]]
name = "a"
type = "Number"
init = 1

[[value]]
name = "constant"
type = "Number"
init = 1
static = true

[[value]]
name = "false"
type = "Bool"
init = false

[[function]]
alias = "sum"
source = "lib://flowstdlib/math/add.toml"

[[connection]]
from = "value/a"
to = "function/sum/i1"

[[connection]]
from = "value/constant"
to = "function/sum/i2"

[[function]]
alias = "add_again"
source = "lib://flowstdlib/math/add.toml"

[[connection]]
from = "function/sum"
to = "function/add_again/i1"

[[connection]]
from = "value/constant"
to = "function/add_again/i2"

[[function]]
alias = "to_string"
source = "lib://flowstdlib/fmt/to_string.toml"

[[connection]]
from = "function/add_again"
to = "function/to_string"

[[function]]
alias = "tap"
source = "lib://flowstdlib/control/tap.toml"

[[function]]
alias = "compare"
source = "lib://flowstdlib/control/compare.toml"

[[connection]]
from = "function/add_again"
to = "function/tap/data"

[[connection]]
from = "function/add_again"
to = "function/compare/left"

[[value]]
name = "two"
type = "Number"
init = 2

[[connection]]
from = "value/two"
to = "function/compare/right"

[[connection]]
from = "value/false"
to = "function/tap/control"

[[connection]]
from = "function/compare/gt"
to = "function/to_string"

[[function]]
alias = "print"
source = "lib://flowrlib/stdio/stdout.toml"

[[connection]]
from = "function/tap"
to = "function/to_string"

[[connection]]
from = "function/to_string"
to = "function/print"