flow = "primitives"

# 1 plus 2 = 3
[[process]]
alias = "sum"
source = "lib://flowstdlib/math/add"
input.i1 = {once = 2}
input.i2 = {once = 1}

# 3 / 2 = 1.5
[[process]]
alias = "divide"
source = "lib://flowstdlib/math/divide"
input.divisor = {once = 2}

[[connection]]
from = "process/sum"
to = "process/divide/dividend"

[[connection]]
from = "process/divide/result"
to = "process/print"

[[process]]
alias = "tap"
source = "lib://flowstdlib/control/tap"
input.control = {once = false}

#compare result (1.5) to 1
[[process]]
alias = "compare"
source = "lib://flowstdlib/control/compare"
input.right = {once = 1}

[[connection]]
from = "process/divide/result"
to = "process/tap/data"

[[connection]]
from = "process/divide/result"
to = "process/compare/left"

[[connection]]
from = "process/compare/gt"
to = "process/print"

[[process]]
alias = "print"
source = "lib://flowruntime/stdio/stdout"

[[connection]]
from = "process/tap"
to = "process/print"