name = "constant"

[[value]]
name = "a"
type = "Number"
init = 1

[[value]]
name = "constant"
type = "Number"
constant = 1

[[value]]
name = "true"
type = "Bool"
init = false

[[function]]
alias = "sum"
source = "lib://flowstdlib/math/add.toml"

[[connection]]
from = "value/a"
to = "function/sum/i1"

[[connection]]
from = "value/constant"
to = "function/sum/i2"

[[function]]
alias = "add_again"
source = "lib://flowstdlib/math/add.toml"

[[connection]]
from = "function/sum"
to = "function/add_again/i1"

[[connection]]
from = "value/constant"
to = "function/add_again/i2"

[[function]]
alias = "to_string"
source = "lib://flowstdlib/fmt/to_string.toml"

[[connection]]
from = "function/add_again"
to = "function/to_string"

[[function]]
alias = "switch"
source = "lib://flowstdlib/control/switch.toml"

[[connection]]
from = "function/add_again"
to = "function/switch/data"

[[connection]]
from = "value/true"
to = "function/switch/control"

[[function]]
alias = "print"
source = "lib://flowstdlib/stdio/stdout.toml"

[[connection]]
from = "function/switch"
to = "function/to_string"

[[connection]]
from = "function/to_string"
to = "function/print"