[package]
name = "ide-native"
version = "0.1.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]

[[bin]]
name = "ide_native"
path = "src/main.rs"

[dependencies]
flowclib = "=0.8.2"
flowrlib = "=0.8.2"
flow_impl = "=0.8.3"
druid = "0.3.0"
serde_json = "1.0"
