[package]
name = "ide-native"
version = "0.1.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]

[lib]
name = "flow"
path = "src/flow.rs"
crate-type = ["dylib"]

[dependencies]
flowclib = "~0.8.1"