language: rust

rust:
- 1.37.0

os:
- osx
- linux

branches:
  only:
    - "master"

before_install:
- make config
- export PATH="$PATH:~/.cargo/bin"

cache:
  cargo: true
  directories:
    - ide/node_modules

before_script:
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.3" mdbook)
  - cargo install-update -a

script: make all

env:
  global:
  - RUSTFLAGS="-C link-dead-code" FLOW_LIB_PATH=$TRAVIS_BUILD_DIR
  matrix:
    secure: pFjhnkemEkZQd3kVvR5alXYhJ4gzHW59pA3FOy4SwUavTFphiDHU+ERMR3bw9uqHANeey3WZLrYH9x7sEwVbH6/nNxnEiTrRZDK/DJrHaOCczH6sU7yNYc+mjtNR/B8b1zA/WMNehIZJivz88bkl0qXheLdmxofN9776RSRK/ER5SdGpOos1rMCHzz7TtUFxAvUV4klf826hZKb3PLuqKBjv0AqmUHrqFrm93nXFpIz7+LSAG5umWYyTCXBIR30mW7iJdjMwCMe/Js4qlXHs9sUPVD/2ipKPKXI8jn8QzEV2zw93tKVZJQqYGMzKeSoxfzIap3Uql8woQnaJs6W8H3JIv47KNvYWI1uDnIbwPPPDdltcV5XCQUUnHT9itvxX5vYNa3p8BO0PHolqmI8TftmRQNhsFdNmp7FF/3Gi34Nif95FGO2K8zMMk0ReKqMYpqYT51Ci3NHXDOGzletwj3fyIcW02PinSMbLzNj5pUN2KKV1qPKsHeGcwnH9XrQKUoLktZS7cPnpRMb0g3QeAjzMnsy4caRLvY58dHxgBuDijZZm45vG/tXQ59BpAJrYk62VGcCNaTR1BRQR626H83aK2Flc6hOZkbjWzXqZXinRq9JODz5LOArhvwIBzOyc+1mIQcjrD07Zqte1/2fHB8F3gtuXpEhkGYg/8Hy9xfY=

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAGES_TOKEN
  local-dir: target/guide/html
  keep-history: false
  on:
    branch: master

notifications:
  email:
  - andrew@mackenzie-serres.net