language: rust
dist: bionic

cache:
  cargo: true
  pip: true
  directories:
    - /usr/local/Cellar/gtk+3
    - /usr/local/Cellar/cairo

matrix:
  include:
  - os: osx
    rust: stable
  - os: linux
    rust: stable
  allow_failures:
    - os: osx

branches:
  only:
    - "master"

addons:
  apt:
    packages:
      - libgtk-3-dev
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev # Required by kcov for code coverage
      - libssl-dev
      - binutils-dev # Required by kcov for code coverage
      - libbfd-dev # Required by kcov for code coverage
      - graphviz # Required to build graphs for the book for gh_pages
  homebrew:
    update: true
    packages:
      - gtk+3
      - cairo

before_install:
  - make travis-config

script:
  - rustc --version
  - make travis

env:
  global:
  - FLOW_LIB_PATH=$TRAVIS_BUILD_DIR
  matrix:
    secure: pFjhnkemEkZQd3kVvR5alXYhJ4gzHW59pA3FOy4SwUavTFphiDHU+ERMR3bw9uqHANeey3WZLrYH9x7sEwVbH6/nNxnEiTrRZDK/DJrHaOCczH6sU7yNYc+mjtNR/B8b1zA/WMNehIZJivz88bkl0qXheLdmxofN9776RSRK/ER5SdGpOos1rMCHzz7TtUFxAvUV4klf826hZKb3PLuqKBjv0AqmUHrqFrm93nXFpIz7+LSAG5umWYyTCXBIR30mW7iJdjMwCMe/Js4qlXHs9sUPVD/2ipKPKXI8jn8QzEV2zw93tKVZJQqYGMzKeSoxfzIap3Uql8woQnaJs6W8H3JIv47KNvYWI1uDnIbwPPPDdltcV5XCQUUnHT9itvxX5vYNa3p8BO0PHolqmI8TftmRQNhsFdNmp7FF/3Gi34Nif95FGO2K8zMMk0ReKqMYpqYT51Ci3NHXDOGzletwj3fyIcW02PinSMbLzNj5pUN2KKV1qPKsHeGcwnH9XrQKUoLktZS7cPnpRMb0g3QeAjzMnsy4caRLvY58dHxgBuDijZZm45vG/tXQ59BpAJrYk62VGcCNaTR1BRQR626H83aK2Flc6hOZkbjWzXqZXinRq9JODz5LOArhvwIBzOyc+1mIQcjrD07Zqte1/2fHB8F3gtuXpEhkGYg/8Hy9xfY=

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAGES_TOKEN
  local-dir: target/html
  keep-history: false
  on:
    branch: master

notifications:
  email:
  - andrew@mackenzie-serres.net

codecov:
  token: 19030176-6eb5-440c-9948-e9eb6a6a2e20

after_success: |
  if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "stable" ]]; then
    make coverage
  fi