language: rust
dist: bionic

cache:
  cargo: true

matrix:
  include:
  - os: osx
    rust: stable
  - os: linux
    rust: stable

env:
  global:
    - FLOW_LIB_PATH=$TRAVIS_BUILD_DIR:$TRAVIS_BUILD_DIR/flowr/src/lib
    - secure: pFjhnkemEkZQd3kVvR5alXYhJ4gzHW59pA3FOy4SwUavTFphiDHU+ERMR3bw9uqHANeey3WZLrYH9x7sEwVbH6/nNxnEiTrRZDK/DJrHaOCczH6sU7yNYc+mjtNR/B8b1zA/WMNehIZJivz88bkl0qXheLdmxofN9776RSRK/ER5SdGpOos1rMCHzz7TtUFxAvUV4klf826hZKb3PLuqKBjv0AqmUHrqFrm93nXFpIz7+LSAG5umWYyTCXBIR30mW7iJdjMwCMe/Js4qlXHs9sUPVD/2ipKPKXI8jn8QzEV2zw93tKVZJQqYGMzKeSoxfzIap3Uql8woQnaJs6W8H3JIv47KNvYWI1uDnIbwPPPDdltcV5XCQUUnHT9itvxX5vYNa3p8BO0PHolqmI8TftmRQNhsFdNmp7FF/3Gi34Nif95FGO2K8zMMk0ReKqMYpqYT51Ci3NHXDOGzletwj3fyIcW02PinSMbLzNj5pUN2KKV1qPKsHeGcwnH9XrQKUoLktZS7cPnpRMb0g3QeAjzMnsy4caRLvY58dHxgBuDijZZm45vG/tXQ59BpAJrYk62VGcCNaTR1BRQR626H83aK2Flc6hOZkbjWzXqZXinRq9JODz5LOArhvwIBzOyc+1mIQcjrD07Zqte1/2fHB8F3gtuXpEhkGYg/8Hy9xfY=

branches:
  only:
    - "master"

addons:
  apt:
    packages:
      - libgtk-3-dev
      - libcurl4-openssl-dev
      - libelf-dev
      - libzmq3-dev
      - libdw-dev # Required by kcov for code coverage
      - libssl-dev
      - binutils-dev # Required by kcov for code coverage
      - libbfd-dev # Required by kcov for code coverage
      - graphviz # Required to build graphs for the book for gh_pages
  homebrew:
    update: true # if not then pango lib for gtk3 won't build
    packages:
      - zmq
      - gtk+3
      - cairo
      - pango

# Docs are only built and deployed in "cron" builds - so only prepare that when needed
before_install:
  - make no-book-config
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "stable" && "$TRAVIS_EVENT_TYPE" == "cron" ]]; then
      make book-config
    fi

# Docs are only built and deployed in "cron" builds
script:
  - RUST_BACKTRACE=full make clippy build test samples
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "stable" && "$TRAVIS_EVENT_TYPE" == "cron" ]]; then
      RUST_BACKTRACE=full make docs
    fi

# Docs are only built and deployed in "cron" builds
deploy:
  provider: pages
  github-token: $GITHUB_PAGES_TOKEN
  skip_cleanup: true
  local-dir: target/html
  keep-history: false
  on:
    branch: master
    condition: $TRAVIS_OS_NAME == "linux" && $TRAVIS_EVENT_TYPE == "cron"

notifications:
  email:
  - andrew@mackenzie-serres.net

after_success: |
  if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "stable" && "$TRAVIS_EVENT_TYPE" != "cron" ]]; then
    FLOW_LIB_PATH=$TRAVIS_BUILD_DIR make coverage
  fi