addons:
  apt:
    packages:
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install -g electron-forge
  - npm install

language: rust
#language: node_js
#node_js:
#  - '8'

rust:
  - 1.19.0

os:
  - osx

script: make test

matrix:
  allow_failures:
    - rust: nightly

notifications:
  email:
    - andrew@mackenzie-serres.net
