language: rust
dist: bionic

# request macOS 10.15.7
# use nightly on linux in order to run grcov for coverage measurement
matrix:
  include:
  - os: linux
    rust: nightly
  - os: osx
    osx_image: xcode12.2
    rust: stable

env:
  global:
    - FLOW_LIB_PATH=$TRAVIS_BUILD_DIR,$TRAVIS_BUILD_DIR/flowr/src/lib
    - secure: pFjhnkemEkZQd3kVvR5alXYhJ4gzHW59pA3FOy4SwUavTFphiDHU+ERMR3bw9uqHANeey3WZLrYH9x7sEwVbH6/nNxnEiTrRZDK/DJrHaOCczH6sU7yNYc+mjtNR/B8b1zA/WMNehIZJivz88bkl0qXheLdmxofN9776RSRK/ER5SdGpOos1rMCHzz7TtUFxAvUV4klf826hZKb3PLuqKBjv0AqmUHrqFrm93nXFpIz7+LSAG5umWYyTCXBIR30mW7iJdjMwCMe/Js4qlXHs9sUPVD/2ipKPKXI8jn8QzEV2zw93tKVZJQqYGMzKeSoxfzIap3Uql8woQnaJs6W8H3JIv47KNvYWI1uDnIbwPPPDdltcV5XCQUUnHT9itvxX5vYNa3p8BO0PHolqmI8TftmRQNhsFdNmp7FF/3Gi34Nif95FGO2K8zMMk0ReKqMYpqYT51Ci3NHXDOGzletwj3fyIcW02PinSMbLzNj5pUN2KKV1qPKsHeGcwnH9XrQKUoLktZS7cPnpRMb0g3QeAjzMnsy4caRLvY58dHxgBuDijZZm45vG/tXQ59BpAJrYk62VGcCNaTR1BRQR626H83aK2Flc6hOZkbjWzXqZXinRq9JODz5LOArhvwIBzOyc+1mIQcjrD07Zqte1/2fHB8F3gtuXpEhkGYg/8Hy9xfY=

branches:
  only:
    - "master"

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libzmq3-dev
      - libdw-dev # Required by kcov for code coverage
      - libssl-dev
      - binutils-dev # Required by kcov for code coverage
      - libbfd-dev # Required by kcov for code coverage
      - graphviz # Required to build graphs for the book for gh_pages
  homebrew:
    packages:
      - zmq

before_install: |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      make config
      cargo install grcov
      rustup component add llvm-tools-preview
    else
      make config
    fi

script: |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export RUSTFLAGS="-Zinstrument-coverage"
      travis_wait 40 make clippy build
      LLVM_PROFILE_FILE="flow-%p-%m.profraw" make test
      grcov . --binary-path target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
      bash <(curl -s https://codecov.io/bash) -f lcov.info
      rm -f lcov.info
    else
      travis_wait 50 make test
    fi

after_success: |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      make docs
      # cleanup things we don't want deployed to gh_pages
      find target/html -name target -type d | xargs rm -rf {}
      find target/html -name .idea | xargs rm -rf {}
      find target/html -name \*.iml | xargs rm -rf {}
      find target/html -name .git | xargs rm -rf {}
      find target/html -name Cargo.toml | xargs rm -rf {}
      find target/html -name manifest.json | xargs rm -rf {}
      find target/html -name test.err | xargs rm -rf {}
      find target/html -name test.input | xargs rm -rf {}
      find target/html -name test.arguments | xargs rm -rf {}
      find target/html -name test.output | xargs rm -rf {}
      find target/html -name expected.output | xargs rm -rf {}
      find target/html -name flow.toml | xargs rm -rf {}
      find target/html -name \*.rs | xargs rm -rf {}
      find target/html -name \*.dump | xargs rm -rf {}
      find target/html -name \*.dot | xargs rm -rf {}
      find target/html -name \*.wasm | xargs rm -rf {}
      find target/html -name \*.lock  | xargs rm -rf {}
      cd target/html && rm -f Makefile .crates.toml .DS_Store .mdbookignore .travis.yml codecov.yml
      rm -rf target/html/flowc/tests/test-flows
      rm -rf target/html/flowc/tests/test-libs
      rm -rf target/html/code/debug
      find target/html -depth -type d -empty -delete
    fi

# Only deploy the docs on linux builds of master branch with stable rust
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_PAGES_TOKEN
  local-dir: target/html
  keep_history: true
  allow_empty_commit: true # Avoid deploy fail on empty commit if nothing has changed (CRON builds)
  on:
    branch: master
    condition: $TRAVIS_OS_NAME == "linux"

notifications:
  email:
  - andrew@mackenzie-serres.net
