[book]
title = "The 'flow' Guide"
authors = ["Andrew Mackenzie"]
description = "A guide to what 'flow' is and how to use it"
multilingual = false
src = "."

[build]
build-dir = "target"
create-missing = false

[output.html]

# enable the "mdbook-linkcheck" renderer
[output.linkcheck]