[book]
title = "The 'flow' Guide"
authors = ["Andrew Mackenzie"]
description = "A guide to 'flow': what it is and how to use it"
multilingual = false
src = "."

[build]
build-dir = "target"
create-missing = false
use-default-preprocessors = false

[output.html]
[preprocessor.links]

[output.linkcheck]