[book]
title = "The 'flow' Guide"
authors = ["Andrew Mackenzie"]
description = "A guide to what 'flow' is and how to use it"
multilingual = false
src = "."

[build]
build-dir = "target/html"
create-missing = false
use-default-preprocessors = false

[output.html]
[preprocessor.links]

# the "mdbook-linkcheck" renderer - when enabling change  build-dir back to "target"
#[output.linkcheck]