[package]
name = "flow"
version = "0.1.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]

[lib]
name = "flow"
path = "src/lib.rs"

[dependencies.yaml-rust]
git = "https://github.com/chyh1990/yaml-rust.git"

[[bin]]
name = "check"
path = "src/check.rs"

[dependencies]
getopts = "0.2"

[[bin]]
name = "flow"
path = "src/flow.rs"