[workspace]
members = ["flowc", "flowr", "flowcore", "flow_impl_derive", "samples"]
default-members = ["flowc", "flowr", "flowcore", "flow_impl_derive", "samples"]

[profile.dev]
split-debuginfo = "unpacked"