[workspace]
members = ["flowc", "flowstdlib", "flowr", "flowcore", "flowmacro", "flowsamples"]
default-members = ["flowc", "flowstdlib", "flowr", "flowcore", "flowmacro", "flowsamples"]

[profile.dev]
split-debuginfo = "unpacked"