[workspace]
members = ["flowc", "flowstdlib", "flowr", "flowcore", "flow_macro", "samples"]
default-members = ["flowc", "flowstdlib", "flowr", "flowcore", "flow_macro", "samples"]

[profile.dev]
split-debuginfo = "unpacked"