[workspace]
members = ["flowc", "flowr", "flowcore", "provider", "flow_impl_derive", "flowstdlib", "samples"]
default-members = ["flowc", "flowr", "flowcore", "provider", "flow_impl_derive", "flowstdlib", "samples"]

[profile.dev]
split-debuginfo = "unpacked"