function = "image_buffer"
source = "image_buffer.rs"
docs = "image_buffer.md"
impure = true

[[input]]
name = "pixel"
type = "Array/number"

[[input]]
name = "value"
type = "Array/number"

[[input]]
name = "size"
type = "Array/number"

[[input]]
name = "filename"
type = "string"