function = "Add"
implementation = "add.rs"

[[input]]
name = "i1"
type = "Number"

[[input]]
name = "i2"
type = "Number"

[[output]]
name = "sum"
type = "Number"

[[output]]
name = "i1"
type = "Number"

[[output]]
name = "i2"
type = "Number"