[package]
name = "flowstdlib"
version = "0.7.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
description = "The standard library for 'flow' programs compiled with the 'flowc' compiler"
license = "MIT"
documentation = "https://github.com/andrewdavidmackenzie/flow/README.md"
homepage = "https://github.com/andrewdavidmackenzie/flow/README.md"
repository = "https://github.com/andrewdavidmackenzie/flow/"
readme = "../README.md"
include = ["src/**/*", "Cargo.toml"]

[lib]
name = "flowstdlib"
path = "src/lib.rs"

[dependencies]
flowrlib = { path = "../flowrlib", version = "~0.7.0" }
serde_json = "1.0"
image = "*"
log = "0.3.8"