[package]
name = "flowstdlib"
version = "0.1.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
build = "build.rs"

[lib]
name = "flowstdlib"
path = "src/lib.rs"

[dependencies]
flowrlib = { path = "../flowrlib" }