[package]
name = "flowstdlib"
version = "0.7.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
description = "The standard library for 'flow' programs compiled with the 'flowc' compiler"
license = "MIT"
documentation = "https://github.com/andrewdavidmackenzie/flow/README.md"
homepage = "https://github.com/andrewdavidmackenzie/flow/README.md"
repository = "https://github.com/andrewdavidmackenzie/flow/"
readme = "../README.md"
include = ["src/**/*", "Cargo.toml"]

build = "flow_lib_build.rs"

[lib]
name = "flowstdlib"
path = "src/lib.rs"

[dependencies]
flowrlib = { path = "../flowrlib", version = "~0.7.0" }
serde_json = "1.0"
image = "*"
log = "0.3.8"

[build-dependencies]
flowclib = { path = "../flowclib", version = "~0.7.0" }
flowrlib = { path = "../flowrlib", version = "~0.7.0" }
glob = "*"
toml = "0.4"
phf_codegen = "*"