[package]
name = "flowstdlib"
version = "0.2.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
description = "The standard library for 'flow' programs compiled with the 'flowc' compiler"
license = "MIT"
build = "build.rs"

[lib]
name = "flowstdlib"
path = "src/lib.rs"

[dependencies]
flowclib = { path = "../flowclib", version = "~0.2.0" }