[package]
name = "flowstdlib"
version = "0.1.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]

[lib]
name = "flowstdlib"
path = "src/flowstdlib.rs"

test = true
doctest = true
bench = true
doc = true

[dependencies]
flowrlib = { path = "../flowrlib" }