[package]
name = "reverse"
version = "0.1.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]

[lib]
name = "reverse"
crate-type = ["cdylib"]

# This field points at where the crate is located, relative to the `Cargo.toml`.
path = "src/reverse.rs"

[dependencies]
serde_json = "1.0"

[workspace]
exclude = [".."]