flow = "reverse-echo"

[[process]]
source = "lib://flowruntime/stdio/readline"

[[process]]
alias = "reverse"
source = "reverse/reverse"

[[process]]
alias = "print"
source = "lib://flowruntime/stdio/stdout"

[[connection]]
name = "normal"
from = "readline/text"
to = "reverse"

[[connection]]
name = "reversed"
from = "reverse/reversed"
to = "print"