name = "reverse-echo"

[[function]]
alias = "read"
source = "lib://flowstdlib/stdio/stdin.toml"

[[function]]
alias = "reverse"
source = "reverse.toml"

[[function]]
alias = "print"
source = "lib://flowstdlib/stdio/stdout.toml"

[[connection]]
name = "normal"
from = "function/read/stdin"
to = "function/reverse/in"

[[connection]]
name = "reversed"
from = "function/reverse/reversed"
to = "function/print/stdout"

[[connection]]
name = "original"
from = "function/reverse/original"
to = "function/print/stdout"