flow = "reverse-echo"
docs = "DESCRIPTION.md"

[[process]]
source = "lib://context/stdio/readline"

[[process]]
source = "lib://flowstdlib/fmt/reverse"

[[process]]
source = "lib://context/stdio/stdout"

[[connection]]
from = "readline/string"
to = "reverse"

[[connection]]
from = "reverse/reversed"
to = "stdout"