flow = "reverse echo"

[[process]]
alias = "read"
source = "lib://runtime/stdio/readline.toml"

[[process]]
alias = "reverse"
source = "src/reverse.toml"

[[process]]
alias = "print"
source = "lib://runtime/stdio/stdout.toml"

[[connection]]
name = "normal"
from = "process/read"
to = "process/reverse"

[[connection]]
name = "reversed"
from = "process/reverse/reversed"
to = "process/print"