name = "reverse-echo"

[[function]]
alias = "read"
source = "lib://flowstdlib/stdio/readline.toml"

[[function]]
alias = "reverse"
source = "reverse.toml"

[[function]]
alias = "print"
source = "lib://flowstdlib/stdio/stdout.toml"

[[connection]]
name = "normal"
from = "function/read"
to = "function/reverse"

[[connection]]
name = "reversed"
from = "function/reverse/reversed"
to = "function/print"