[package]
name = "flowc"
version = "0.2.0-dev"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
description = "A compiler for 'flow' programs"
license = "MIT"
documentation = "https://github.com/andrewdavidmackenzie/flow/README.md"
homepage = "https://github.com/andrewdavidmackenzie/flow/README.md"
repository = "https://github.com/andrewdavidmackenzie/flow/"
readme = "https://github.com/andrewdavidmackenzie/flow/README.md"

[[bin]]
name = "flowc"
path = "src/flowc.rs"

[dependencies]
clap = "~2.27.1"
flowclib = { path = "../flowclib", version = "~0.2.0" }
log = "0.3.8"
url = "~1.6.0"
tempdir = "~0.3.5"