[package]
name = "flowc"
version = "0.4.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
description = "A compiler for 'flow' programs"
license = "MIT"
documentation = "https://github.com/andrewdavidmackenzie/flow/README.md"
homepage = "https://github.com/andrewdavidmackenzie/flow/README.md"
repository = "https://github.com/andrewdavidmackenzie/flow/"
readme = "https://github.com/andrewdavidmackenzie/flow/README.md"

[[bin]]
name = "flowc"
path = "src/flowc.rs"

[dependencies]
clap = "~2.27.1"
flowclib = { path = "../flowclib", version = "~0.7.0" }
simplog = "1.0.3"
log = "0.3.8"
url = "~1.6.0"
tempdir = "~0.3.5"
curl = "~0.4.11"
simpath = "~1.2"
glob = "~0.2.11"

[package.metadata.bundle]
identifier = "net.mackenzie-serres.flow.flowc"
icon = ["icons/32x32.png", "icons/128x128.png"]
resources = ["lib"]