[package]
name = "flowc"
version = "0.8.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
description = "A compiler for 'flow' programs"
license = "MIT"
documentation = "https://github.com/andrewdavidmackenzie/flow/README.md"
homepage = "https://github.com/andrewdavidmackenzie/flow/README.md"
repository = "https://github.com/andrewdavidmackenzie/flow/"
readme = "https://github.com/andrewdavidmackenzie/flow/README.md"
edition = "2018"

[[bin]]
name = "flowc"
path = "src/main.rs"

[features]
default = ["debugger"]
debugger = []
online_tests = []

[dependencies]
clap = "~2"
flowclib = { path = "../flowclib", version = "~0.8.0" }
flowrlib = { path = "../flowrlib", version = "~0.8.0" }
provider = { path = "../provider", version = "~0.8.0" }
flowr = { path = "../flowr" , version = "~0.8.0" }
simplog = "1.1.1"
log = "0.4.6"
url = "~1.6.0"
tempdir = "~0.3.5"
curl = "~0.4.11"
simpath = "~1.3"
glob = "~0.2.11"
serde_json = "1.0"
error-chain = "0.12.1"
