[package]
name = "flowc"
version = "0.1.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]

[[bin]]
name = "flowc"
path = "src/flowc.rs"

[dependencies]
clap = "~2.27.1"
glob = "*"
flowclib = { path = "../flowclib" }
log = "0.3.8"
url = "*"