[package]
name = "flowc"
version = "0.1.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
description = "A compiler for 'flow' programs"
license = "MIT"

[[bin]]
name = "flowc"
path = "src/flowc.rs"

[dependencies]
clap = "~2.27.1"
flowclib = { path = "../flowclib", version = "~0.2.0" }
log = "0.3.8"
url = "*"
tempdir = "*"