[package]
name = "range_split"
version = "0.11.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
edition = "2018"

[lib]
name = "range_split"
crate-type = ["cdylib"]
path = "range_split.rs"

[profile.release]
debug = false
lto = true
codegen-units = 1
opt-level = 's' # Optimize for size
panic = 'abort' # About unwinding code

[dependencies]
flowcore = {path = "../../../flowcore", version = "0.40.1"}

flow_macro = {path = "../../../flow_macro", version = "0.40"}
serde_json = "1.0"

[workspace]
exclude = ["../../.."]
