flow = "echo"

[[process]]
alias = "stdin"
source = "lib://flowr/stdio/readline.toml"

[[process]]
alias = "print"
source = "lib://flowr/stdio/stdout.toml"

[[connection]]
from = "process/stdin"
to = "process/print"