name = "echo"

[[function]]
alias = "read"
source = "lib://flowstdlib/stdio/stdin.toml"

[[function]]
alias = "print"
source = "lib://flowstdlib/stdio/stdout.toml"

[[connection]]
name = "echo"
from = "function/read"
to = "function/print/stdout"