flow = "echo"

[[process]]
alias = "stdin"
source = "lib://flowrlib/stdio/stdin.toml"

[[process]]
alias = "print"
source = "lib://flowrlib/stdio/stdout.toml"

[[connection]]
from = "process/stdin"
to = "process/print"