[[function]]
alias = "stdin"
source = "lib://flowstdlib/stdio/stdin.toml"

[[function]]
alias = "print"
source = "lib://flowstdlib/stdio/stdout.toml"

[[connection]]
name = "echo"
from = "function/stdin"
to = "function/print"