flow = "echo"

[[function]]
alias = "stdin"
source = "lib://flowrlib/stdio/stdin.toml"

[[function]]
alias = "print"
source = "lib://flowrlib/stdio/stdout.toml"

[[connection]]
from = "function/stdin"
to = "function/print"