[package]
name = "flowui"
version = "0.1.2"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]

[[bin]]
name = "ui"
path = "src/ui.rs"

[dependencies]
flowclib = { path = "../flowclib", version = "^0.3" }
