function = "reverse"
source = "reverse.rs"

[[input]]
type = "String" # The String to reverse

[[output]]
name = "reversed" # - The input string reversed
type = "String"

[[output]]
name = "original" # - The original input string
type = "String"