flow = "line echo"

[[function]]
alias = "readline"
source = "lib://flowrlib/stdio/readline.toml"

[[function]]
alias = "print"
source = "lib://flowrlib/stdio/stdout.toml"

[[connection]]
name = "echo"
from = "function/readline"
to = "function/print"