flow = "line echo"

[[process]]
alias = "readline"
source = "lib://flowrlib/stdio/readline.toml"

[[process]]
alias = "print"
source = "lib://flowrlib/stdio/stdout.toml"

[[connection]]
name = "echo"
from = "process/readline"
to = "process/print"