flow = "pass if lte"

[[input]]
name = "in"
type = "Number"

[[input]]
name = "max"
type = "Number"

[[output]]
name = "passed"
type = "Number"

[[output]]
name = "blocked"
type = "Bool"

[[output]]
name = "control"
type = "Number"

[[process]]
alias = "tap"
source = "lib://flowstdlib/control/tap.toml"

[[process]]
alias = "compare"
source = "lib://flowstdlib/control/compare.toml"

[[connection]]
from = "input/in"
to = "process/tap/data"

[[connection]]
from = "input/in"
to = "process/compare/left"

[[connection]]
from = "input/max"
to = "process/compare/right"

[[connection]]
from = "process/compare/lte"
to = "process/tap/control"

[[connection]]
from = "process/tap"
to = "output/passed"

[[connection]]
from = "process/compare/gt"
to = "output/blocked"

[[connection]]
from = "input/max"
to = "output/control"