flow = "check if prime"

# Inputs and Outputs
[[input]]
name = "candidate"
type = "Number"

[[output]]
name = "prime"
type = "Number"

[[output]]
name = "done"
type = "Bool"


# Generate a series of possible divisors of the candidate, from 1 up to the candidate
[[value]]
name = "lowest-divisor"
type = "Number"
init = 1

[[connection]]
from = "value/lowest-divisor"
to = "process/divisor-range/start"

[[connection]]
from = "input/candidate"
to = "process/divisor-range/limit"

[[process]]
alias = "divisor-range"
source = "../range/range.toml"

[[connection]]
from = "process/divisor-range/done"
to = "output/done"

######################################


# TODO ADM Debugging - shortcut and just output all the divisors generated
[[connection]]
from = "process/divisor-range/series"
to = "output/prime"


######################################


# divide the candidate by the divisor
#[[process]]
#alias = "divide"
#source = "lib://flowstdlib/math/divide.toml"

#[[connection]]
#from = "process/divisor-range/max"
#to = "process/divide/dividend"

#[[connection]]
#from = "process/divisor-range/series"
# to = "process/divide/divisor"


#check if the remainder is equal to 0
#[[value]]
#name = "zero"
#type = "Number"
#init = 0
#static = true

#[[process]]
#alias = "zero_remainder"
#source = "lib://flowstdlib/control/compare.toml"

#[[connection]]
#from = "value/zero"
#to = "process/zero_remainder/left"

#[[connection]]
#from = "process/divide/remainder"
#to = "process/zero_remainder/right"


# if the remainder was 0 then let the value pass to output
#[[process]]
#alias = "tap"
#source = "lib://flowstdlib/control/tap.toml"

#[[connection]]
#from = "process/zero_remainder/equal"
#to = "process/tap/control"

#[[connection]]
#from = "process/divide/dividend"
#to = "process/tap/data"

# TODO AMD
#[[connection]]
#from = "process/tap"
#to = "process/to_string"