[package]
name = "join"
version = "0.11.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
edition = "2018"

[lib]
name = "join"
crate-type = ["cdylib"]
path = "join.rs"

[profile.release]
debug = false
lto = true
opt-level = 's'

[dependencies]
flowcore = {version = "=0.34.8", default-features = false}
flow_impl_derive = "=0.34.7"

serde_json = "1.0"

[workspace]
exclude = ["../../../"]
