function = "join"
source = "join.rs"
docs = "join.md"
build_script = "Cargo.toml"

[[input]]
name = "data" # - the data we wish to control the flow of
type = "Value"

[[input]]
name = "control" # - a second value we wait on
type = "Value"

[[output]]
type = "Value"