[package]
name = "flowclib"
version = "0.1.1"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]

[lib]
name = "flowclib"
path = "src/lib.rs"

test = true
doctest = true
bench = true
doc = true

[dependencies]
yaml-rust = "~0.3.5"
toml = "0.4"
serde_derive = "*"
serde = "*"
flowrlib = { path = "../flowrlib" }
flowstdlib = { path = "../flowstdlib" }
log = "0.3.8"
glob = "*"
strfmt = "0.1.5"
url = "*"
curl = "*"