[package]
name = "flowclib"
version = "0.2.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
description = "A library for compiling 'flow' programs used by the 'flowc' compiler"
license = "MIT"

[lib]
name = "flowclib"
path = "src/lib.rs"

test = true
doctest = true
bench = true
doc = true

[dependencies]
yaml-rust = "~0.3.5"
toml = "0.4"
serde_derive = "*"
serde = "*"
flowrlib = { path = "../flowrlib", version = "~0.2.0" }
flowstdlib = { path = "../flowstdlib", version = "~0.2.0" }
log = "0.3.8"
glob = "*"
strfmt = "0.1.5"
url = "*"
curl = "*"