# Two values are used:
#     "HEAD" which the "rightmost" number in the series being produced
#     "HEAD-1" which the "rightmost" -1 number in the series being produced
# Both are initialized with the integer 1
[[value]]
name = "HEAD-1"
type = "Number"
init = 1

[[value]]
name = "HEAD"
type = "Number"
init = 1

# The function "add" from the standard library is used, but aliased to be able to reference it using "sum"
[[function]]
alias = "sum"
source = "lib://flowstdlib/math/add.toml"

# The function "stdout" from the standard library is used, but aliased to be able to reference it using "print"
[[function]]
alias = "print"
source = "lib://flowstdlib/stdio/stdout.toml"

# All the required connections between functions and values to create the flow follow, as per diagram
[[connection]]
from = "value/HEAD-1"
to = "function/sum/i1"

[[connection]]
from = "value/HEAD"
to = "value/HEAD-1"

[[connection]]
from = "value/HEAD"
to = "function/sum/i2"

[[connection]]
from = "function/sum"
to = "value/HEAD"

[[connection]]
from = "value/HEAD-1"
to = "function/print"