flow = "first flow"

# Two values are used:
#     "HEAD" which the "rightmost" number in the series being produced
#     "HEAD-1" which the "rightmost" -1 number in the series being produced
# Both are initialized with the integer 1
[[process]]
alias = "HEAD-1"
source = "lib://flowstdlib/data/buffer"
input.default = {once = 1}

[[process]]
alias = "HEAD"
source = "lib://flowstdlib/data/buffer"
input.default = {once = 1}

# The function "add" from the standard library is used, but aliased to be able to reference it using "sum"
[[process]]
alias = "sum"
source = "lib://flowstdlib/math/add"

# The function "stdout" from the standard library is used, but aliased to be able to reference it using "print"
[[process]]
alias = "print"
source = "lib://flowruntime/stdio/stdout"

# All the required connections between functions and values to create the flow follow, as per diagram
[[connection]]
from = "HEAD-1"
to = "sum/i1"

[[connection]]
from = "HEAD"
to = "HEAD-1"

[[connection]]
from = "HEAD"
to = "sum/i2"

[[connection]]
from = "sum"
to = "HEAD"

[[connection]]
from = "HEAD-1"
to = "print"