flow = "hello world simple"

[[value]]
name = "message"
type = "String"
init = "Hello World!"

[[process]]
alias = "print"
source = "lib://flowrlib/stdio/stdout.toml"

[[connection]]
from = "value/message"
to = "process/print"