[[value]]
name = "message"
type = "String"
init = "Hello World!"

[[function]]
alias = "print"
source = "lib://flowstdlib/stdio/stdout.toml"

[[connection]]
from = "value/message"
to = "function/print"