name = "hello-world-simple"

[[value]]
name = "message"
type = "String"
value = "Hello World!"

[[function]]
alias = "print"
source = "lib://std/stdio/stdout.toml"

[[connection]]
name = "message"
from = "value/message"
to = "function/print/stdout"