flow = "prime"

####### All numbers
# Read the limit from the command line
[[process]]
alias = "args"
source = "lib://flowruntime/args/get.toml"

[[connection]]
from = "process/args/1"
to = "process/to_number"

[[process]]
alias = "to_number"
source = "lib://flowstdlib/fmt/to_number"

[[connection]]
from = "process/to_number"
to = "process/candidates/end"

# Generate the range of numbers from 1..limit of possible primes
[[process]]
alias = "candidates"
source = "lib://flowstdlib/math/sequence"
input.start = {once = 1}
input.step = {once = 1}

####### Composites
[[process]]
alias = "composites"
source = "composites.toml"

[[connection]]
from = "process/to_number"
to = "process/composites/limit"

####### Output
# Output result to stdout
[[connection]]
from = "process/composites/composites"
to = "process/print"

[[process]]
alias = "print"
source = "lib://flowruntime/stdio/stdout"
