[package]
name = "router"
version = "0.1.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
edition = "2018"

[lib]
name = "read_section"
crate-type = ["cdylib"]
path = "src/read_section.rs"

[dependencies]
flow_impl = { path = "../../flow_impl"}
flow_impl_derive = { path = "../../flow_impl/flow_impl_derive" }
serde_json = "1.0"

[workspace]
exclude = ["../../"]
