name = "router"

[[function]]
alias = "readline"
source = "lib://flowstdlib/stdio/readline.toml"

[[connection]]
from = "function/readline"
to = "function/read_section"

[[function]]
alias = "read_section"
source = "read_section.toml"

[[connection]]
from = "function/read_section/a"
to = "function/print"

[[function]]
alias = "print"
source = "lib://flowstdlib/stdio/stdout.toml"