flow = "router"

[[process]]
alias = "readline"
source = "lib://flowruntime/stdio/readline"

[[connection]]
from = "process/readline"
to = "process/read_section"

[[process]]
alias = "read_section"
source = "read_section/read_section"

[[connection]]
from = "process/read_section"
to = "process/print"

[[process]]
alias = "print"
source = "lib://flowruntime/stdio/stdout"