flow = "router"

[[process]]
alias = "readline"
source = "lib://runtime/stdio/readline.toml"

[[connection]]
from = "process/readline"
to = "process/read_section"

[[process]]
alias = "read_section"
source = "read_section/read_section.toml"

[[connection]]
from = "process/read_section"
to = "process/to_string"

[[process]]
alias = "to_string"
source = "lib://flowstdlib/fmt/to_string.toml"

[[connection]]
from = "process/to_string"
to = "process/print"

[[process]]
alias = "print"
source = "lib://runtime/stdio/stdout.toml"