flow = "matrix_mult"

[[process]]
alias = "multiply"
source = "multiply"
input.a = { Once =  [[1, 2], [3, 4]] }
input.b = { Once =  [[5, 6], [7, 8]] }

[[process]]
alias = "print"
source = "lib://flowruntime/stdio/stdout"

[[connection]]
from = "multiply/product"
to = "print"