flow = "mandlebrot"

# Args
[[process]]
alias = "args"
source = "lib://flowruntime/args/get"

# debug
[[connection]]
from = "args/1"
to = "stdout"

# parse bounds
[[process]]
alias = "split_bounds"
source = "lib://flowstdlib/data/split"
input.separator ={ always = "x" }

# looopback
[[connection]]
from = "split_bounds/partial"
to = "split_bounds/string"

[[connection]]
from = "args/2"
to = "split_bounds/string"

# parse upper left
[[process]]
alias = "split_upper_left"
source = "lib://flowstdlib/data/split"
input.separator ={ always = "," }

# looopback
[[connection]]
from = "split_upper_left/partial"
to = "split_upper_left/string"

[[connection]]
from = "args/3"
to = "split_upper_left/string"

# parse lower right
[[process]]
alias = "split_lower_right"
source = "lib://flowstdlib/data/split"
input.separator ={ always = "," }

# looopback
[[connection]]
from = "split_lower_right/partial"
to = "split_lower_right/string"

[[connection]]
from = "args/4"
to = "split_lower_right/string"

# debug
[[process]]
source = "lib://flowruntime/stdio/stdout"

[[connection]]
from = "split_bounds/token"
to = "stdout"

[[connection]]
from = "split_upper_left/token"
to = "stdout"

[[connection]]
from = "split_lower_right/token"
to = "stdout"


## Subflow 'render'
#[[process]]
#alias = "render"
#source = "render"
#
#[[connection]]
#from = "parse_bounds"
#to = "render/bounds"
#
#[[connection]]
#from = "parse_upper_left"
#to = "render/upper_left"
#
#[[connection]]
#from = "parse_lower_right"
#to = "render/lower_right"

#

# Format Bitmap
#[[process]]
#alias = "format_bitmap"
#source = "lib://flowstdlib/img/format_png"

#[[connection]]
#from = "render/bitmap_bounds"
#to = "format_bitmap/bounds"

#[[connection]]
#from = "render/bytes"
#to = "format_bitmap/bytes"


# Write Bitmap to a file
#[[process]]
#alias = "write_file"
#source = "lib://flowruntime/file/file_write"

#[[connection]]
#from = "args/0"
#to = "write_file/filename"

#[[connection]]
#from = "format_bitmap"
#to = "write_file/bytes"
