flow = "mandlebrot"

# Args
[[process]]
alias = "args"
source = "lib://flowruntime/args/get"


# Bounds
[[process]]
alias = "parse_bounds"
source = "src/parse_pair/parse_pair"

[[process]]
alias = "bounds_separator"
source = "lib://flowstdlib/data/buffer/buffer"
input.default = {always =  "x"}

[[connection]]
from = "args/2"
to = "parse_bounds/input"

[[connection]]
from = "bounds_separator"
to = "parse_bounds/separator"

#

# Points Separator
[[process]]
alias = "point_separator"
source = "lib://flowstdlib/data/buffer/buffer"
input.default = {always =  ","}

# Upper Left Coordinate
[[process]]
alias = "parse_upper_left"
source = "src/parse_pair/parse_pair"

[[connection]]
from = "point_separator"
to = "parse_upper_left/separator"

[[connection]]
from = "args/3"
to = "parse_upper_left/input"

#

# Lower Right Coordinate
[[process]]
alias = "parse_lower_right"
source = "src/parse_pair/parse_pair"

[[connection]]
from = "point_separator"
to = "parse_lower_right/separator"

[[connection]]
from = "args/4"
to = "parse_lower_right/input"


# Subflow 'render'
[[process]]
alias = "render"
source = "render"

[[connection]]
from = "parse_bounds"
to = "render/bounds"

[[connection]]
from = "parse_upper_left"
to = "render/upper_left"

[[connection]]
from = "parse_lower_right"
to = "render/lower_right"

#

# Format Bitmap
#[[process]]
#alias = "format_bitmap"
#source = "lib://flowstdlib/img/format_png"

#[[connection]]
#from = "render/bitmap_bounds"
#to = "format_bitmap/bounds"

#[[connection]]
#from = "render/bytes"
#to = "format_bitmap/bytes"


# Write Bitmap to a file
#[[process]]
#alias = "write_file"
#source = "lib://flowruntime/file/file_write"

#[[connection]]
#from = "args/0"
#to = "write_file/filename"

#[[connection]]
#from = "format_bitmap"
#to = "write_file/bytes"
