function = "CompareSwitch"
implementation = "compare_switch.rs"

[[input]]
name = "left"

[[input]]
name = "right"

[[output]]
name = "equal"

[[output]]
name = "right-lt"

[[output]]
name = "right-lte"

[[output]]
name = "right-gt"

[[output]]
name = "right-gte"

[[output]]
name = "left-lt"

[[output]]
name = "left-lte"

[[output]]
name = "left-gt"

[[output]]
name = "left-gte"