function = "compare_switch"
source = "compare_switch.rs"

[[input]]
name = "left" # - left hand input
type = "Number"

[[input]]
name = "right" # - right hand input
type = "Number"

[[output]]
name = "equal" # - outputs right hand value if the two values are equal
type = "Number"

[[output]]
name = "right-lt" # - outputs right hand value if the left hand value is less than the right hand value
type = "Number"

[[output]]
name = "right-lte" # - outputs right hand value if the left hand value is less than or equal to the right hand value
type = "Number"

[[output]]
name = "right-gt" # - outputs right hand value if the left hand value is greater than the right hand value
type = "Number"

[[output]]
name = "right-gte" # - outputs right hand value if the left hand value is greater than or equal to the right hand value
type = "Number"

[[output]]
name = "left-lt" # - outputs left hand value if the left hand value is less than the right hand value
type = "Number"

[[output]]
name = "left-lte" # - outputs left hand value if the left hand value is less than or equal to the right hand value
type = "Number"

[[output]]
name = "left-gt" # - outputs left hand value if the left hand value is greater than the right hand value
type = "Number"

[[output]]
name = "left-gte" # - outputs left hand value if the left hand value is greater than or equal to the right hand value
type = "Number"