flow = "prime"

# Generate a list of candidates from 1 up to the max specified in arg 1
[[process]]
alias = "args"
source = "lib://flowr/args/get.toml"

[[process]]
alias = "generate-candidates"
source = "generate_candidates.toml"

[[connection]]
from = "process/args/1"
to = "process/generate-candidates/limit"

[[connection]]
from = "process/generate-candidates/candidates"
to = "process/pass-if-prime/candidate"

[[process]]
alias = "pass-if-prime"
source = "pass_if_prime.toml"

# Convert any prime that was output to a string and print it
[[process]]
alias = "to_string"
source = "lib://flowstdlib/fmt/to_string.toml"

[[connection]]
from = "process/pass-if-prime/prime"
to = "process/to_string"

[[process]]
alias = "print"
source = "lib://flowr/stdio/stdout.toml"

[[connection]]
from = "process/to_string"
to = "process/print"