# Generate a list of candidates from 1 up to the max specified in arg 1
[[function]]
alias = "args"
source = "lib://flowrlib/env/args.toml"

[[flow]]
alias = "generate-candidates"
source = "generate_candidates.toml"

[[connection]]
from = "function/args/1"
to = "flow/generate-candidates/limit"

[[connection]]
from = "flow/generate-candidates/candidates"
to = "flow/check-if-prime/candidate"

[[flow]]
alias = "check-if-prime"
source = "check_if_prime.toml"

[[connection]]
from = "flow/check-if-prime/prime"
to = "function/to_string"

# Convert any prime that was output to a string and print it
[[function]]
alias = "to_string"
source = "lib://flowstdlib/fmt/to_string.toml"

[[connection]]
from = "function/to_string"
to = "function/print"

[[function]]
alias = "print"
source = "lib://flowrlib/stdio/stdout.toml"