flow = "prime"

# Generate a list of candidates from 1 up to the max specified in arg 1
[[process]]
alias = "args"
source = "lib://runtime/args/get"

[[process]]
alias = "generate-candidates"
source = "generate_candidates"

[[connection]]
from = "process/args/1"
to = "process/generate-candidates/limit"

[[connection]]
from = "process/generate-candidates/candidates"
to = "process/check-if-prime/candidate"

[[process]]
alias = "check-if-prime"
source = "check_if_prime"

# Convert any prime that was output to a string and print it
[[process]]
alias = "to_string"
source = "lib://flowstdlib/fmt/to_string"

[[connection]]
from = "process/check-if-prime/prime"
to = "process/to_string"

[[process]]
alias = "print"
source = "lib://runtime/stdio/stdout"

[[connection]]
from = "process/to_string"
to = "process/print"