flow = "generate candidates"

# Generate a list of candidates from 1 up to the max specified in arg 1
[[input]]
name = "limit"
type = "String"

[[output]]
name = "candidates"
type = "Number"

[[connection]]
from = "input/limit"
to = "process/to_number"

[[process]]
alias = "to_number"
source = "lib://flowstdlib/fmt/to_number.toml"

[[connection]]
from = "process/to_number"
to = "process/candidates-range/limit"

[[value]]
name = "lowest-candidate"
type = "Number"
init = 1

[[connection]]
from = "value/lowest-candidate"
to = "process/candidates-range/start"

[[process]]
alias = "candidates-range"
source = "../range/range.toml"

[[connection]]
from = "process/candidates-range/series"
to = "output/candidates"