[package]
name = "reverse"
version = "0.11.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
edition = "2018"

[lib]
name = "reverse"
crate-type = ["cdylib"]
path = "reverse.rs"

[profile.release]
debug = true
lto = true
codegen-units = 1
opt-level = 's' # Optimize for size
panic = 'abort' # About unwinding code

[dependencies]
# flowcore - no "code" feature, only used for trait definition
flowcore = { version = "0.40", path = "../../../flowcore", default-features = false }
flow_impl_derive = { version = "0.40", path = "../../../flow_impl_derive" }
serde_json = { version = "1.0", default-features = false }

[workspace]
exclude = ["../../.."]
