function = "reverse"
source = "reverse.rs"
type = "rust"

[[input]]
type = "String"

[[output]]
name = "reversed"
type = "String"

# TODO remove this now that inputs are always available on the outputs?
[[output]]
name = "original"
type = "String"