[package]
name = "hello-world"
version = "0.0.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]

[[bin]]
name = "hello-world"
path = "src/main.rs"

[dependencies]
flowrlib = { path = "../flowrlib" }
flowstdlib = { path = "../flowstdlib" }
log = "*"