flow = "hello-world-include"

[[process]]
alias = "print"
source = "lib://flowruntime/stdio/stdout"

[[process]]
alias = "hello"
source = "../hello-world/flow1"

[[connection]]
name = "message"
from = "hello/out"
to = "print"