name = "hello-world-include-context"

[[function]]
alias = "print"
source = "../hello-world/terminal.toml"

[[flow]]
alias = "hello"
source = "../hello-world/flow1.toml"

[[connection]]
name = "message"
from = "flow/hello/out"
to = "function/print/stdout"