[package]
name = "to_json"
version = "0.11.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
edition = "2018"

[lib]
name = "to_json"
crate-type = ["cdylib"]
path = "to_json.rs"

[profile.release]
debug = false
lto = true
codegen-units = 1
opt-level = 's' # Optimize for size
panic = 'abort' # About unwinding code

[dependencies]
flowcore = {version = "=0.34.8", default-features = false}
flow_impl_derive = "=0.34.7"
serde_json = "1.0"

[workspace]
exclude = ["../../../"]
