function = "to_json"
source = "to_json.rs"
docs = "to_json.md"
build_script = "Cargo.toml"

[[input]]
type = "String" # The String to convert

[[output]]
type = "Value" # The Json equivalent of String input