[package]
name = "flowmacro"
version = "0.43.0"
description = "Definition of a 'flow' attribute macro to help write implementations"
license = "MIT"
documentation = "https://github.com/andrewdavidmackenzie/flow/flowmacro/README.md"
homepage = "http://andrewdavidmackenzie.github.io/flow/"
repository = "https://github.com/andrewdavidmackenzie/flow/"
readme = "README.md"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
edition = "2021"

[badges]
maintenance = { status = "actively-developed" }

[lib]
proc-macro = true

[dependencies]
syn = { version = "~1.0", features =["full"] } #Full is required for ItemFn in macro parsing
quote = "~1.0"
flowcore = {path = "../flowcore", version = "0.43.0"}
toml = "0.5.8"
proc-macro2 = "1.0"
