[package]
name = "flowsamples"
version = "0.22.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
readme = "README.md"
description = "A set of sample 'flow' programs"
license = "MIT"
documentation = "https://github.com/andrewdavidmackenzie/flow/samples/README.md"
homepage = "http://andrewdavidmackenzie.github.io/flow/"
repository = "https://github.com/andrewdavidmackenzie/flow/"
edition = "2018"

build = "build.rs"

# Avoid a bunch of files that are generated as part of the samples building and/or running
exclude = ["**/*.dump", "**/*.err", "**/*.dot", "**/*.svg", "manifest.json", "failed.output", "Cargo.lock",
           ".gitignore"]

[[bin]]
name = "samples"
path = "main.rs"

[build-dependencies]
flowc = {path = "../flowc", version = "0.22.0" }

[dependencies.flowr]
path = "../flowr"
version = "0.22.0"
features = ["debugger", "metrics", "checks"]

