[package]
name = "mandlebrot"
version = "0.11.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]

edition = "2018"

[dependencies]
serde_json = "1.0"
num = "0.3.0"
image = "=0.23.10"
rayon = "*"
tempdir = "*"
dir-diff = "*"

[workspace]
exclude = [".."]