flow = "hello world"

[[process]]
alias = "print"
source = "lib://runtime/stdio/stdout.toml"

[[process]]
alias = "hello"
source = "flow1.toml"

[[connection]]
name = "message"
from = "process/hello/out"
to = "process/print"