name = "hello-world-context"

[[function]]
alias = "print"
source = "lib://flowstdlib/stdio/stdout.toml"

[[flow]]
alias = "hello"
source = "flow1.toml"

[[connection]]
name = "message"
from = "flow/hello/out"
to = "function/print/stdout"