flow = "hello world"

[[function]]
alias = "print"
source = "lib://flowrlib/stdio/stdout.toml"

[[process]]
alias = "hello"
source = "flow1.toml"

[[connection]]
name = "message"
from = "flow/hello/out"
to = "function/print"