name = "hello-world-toml-context"

[[function]]
alias = "print"
source = "terminal.toml"

[[flow]]
alias = "hello"
source = "flow1.toml"

[[connection]]
name = "message"
from = "flow/hello/out"
to = "function/print/stdout"