flow = "hello world"

[[process]]
alias = "print"
source = "lib://flowruntime/stdio/stdout"

[[process]]
alias = "hello"
source = "flow1"

[[connection]]
name = "message"
from = "process/hello/out"
to = "process/print"