flow = "flow1"

# TODO this could be removed when we are able to initialize an output with a value
[[process]]
alias = "message"
source = "lib://flowstdlib/data/buffer"
input.default = {once = "Hello World!"}

[[output]]
name = "out"
type = "String"

[[connection]]
name = "message"
from = "process/message"
to = "output/out"