name = "hello-world-flow1"

[[value]]
name = "message"
type = "String"
value = "Hello World!"

[[output]]
name = "out"
type = "String"

[[connection]]
name = "message"
from = "value/message"
to = "output/out"