[package]
name = "index"
version = "0.11.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
edition = "2018"

[lib]
name = "index"
crate-type = ["cdylib"]
path = "index.rs"

[profile.release]
debug = false
lto = true
codegen-units = 1
opt-level = 's' # Optimize for size
panic = 'abort' # About unwinding code

[dependencies]
flowcore = { version = "0.42", path = "../../../flowcore"}
flow_macro = { path = "../../../flow_macro", version = "0.42" }
serde_json = "1.0"

[workspace]
exclude = ["../../.."]
