flow = "sequence"

# IO declarations
[[input]]
name = "start"
type = "Number"

[[input]]
name = "end"
type = "Number"

[[output]]
name = "sequence"
type = "Number"

[[output]]
name = "max"
type = "Number"

[[output]]
name = "done"
type = "Bool"

[[connection]]
from = "input/start"
to = "process/pilte/in"

# A store for the limit value that always refreshes itself, so it's value is always available
[[value]]
name = "limit-store"
type = "Number"
static = true

[[connection]]
from = "input/end"
to = "value/limit-store"

# pass if less than or equal, add one and loop
[[process]]
alias = "pilte"
source = "lib://flowstdlib/control/pass_if_lte.toml"

[[process]]
alias = "add"
source = "lib://flowstdlib/math/add.toml"
input.i2 = {constant = 1}

[[connection]]
from = "value/limit-store"
to = "process/pilte/max"

[[connection]]
from = "process/pilte/passed"
to = "output/sequence"

[[connection]]
from = "process/pilte/passed"
to = "process/add/i1"

[[connection]]
from = "process/add"
to = "process/pilte/in"

[[connection]]
from = "process/pilte/blocked"
to = "output/done"

[[connection]]
from = "value/limit-store"
to = "output/max"