flow = "sequence"

# IO declarations
[[input]]
name = "start"
type = "Number"

[[input]]
name = "end"
type = "Number"

[[output]]
name = "sequence"
type = "Number"

[[output]]
name = "min"
type = "Number"

[[output]]
name = "max"
type = "Number"

[[output]]
name = "done"
type = "Bool"

# IO taps
[[value]]
name = "start-signal"
type = "Bool"
init = true

[[process]]
alias = "limit-gate"
source = "lib://flowstdlib/control/tap.toml"

[[process]]
alias = "start-gate"
source = "lib://flowstdlib/control/tap.toml"

[[connection]]
from = "value/start-signal"
to = "process/limit-gate/control"

[[connection]]
from = "input/end"
to = "process/limit-gate/data"

[[connection]]
from = "value/start-signal"
to = "process/start-gate/control"

[[connection]]
from = "input/start"
to = "process/start-gate/data"


# A store for the limit value that always refreshes itself, so it's value is always available
[[value]]
name = "limit-store"
type = "Number"
static = true

[[connection]]
from = "process/limit-gate"
to = "value/limit-store"

[[connection]]
from = "process/start-gate"
to = "process/pilte/in"

# pass if less than or equal, add one and loop
[[process]]
alias = "pilte"
source = "lib://flowstdlib/control/pass_if_lte.toml"

[[process]]
alias = "add"
source = "lib://flowstdlib/math/add.toml"

[[connection]]
from = "value/limit-store"
to = "process/pilte/max"

[[connection]]
from = "process/pilte/passed"
to = "output/sequence"

[[connection]]
from = "process/pilte/passed"
to = "process/add/i1"

[[value]]
name = "one"
type = "Number"
init = 1
static = true

[[connection]]
from = "value/one"
to = "process/add/i2"

[[connection]]
from = "process/add"
to = "process/pilte/in"

[[connection]]
from = "input/start"
to = "output/min"

[[value]]
name = "range-done"
type = "Bool"
init = true
static = true

[[process]]
alias = "when-done"
source = "lib://flowstdlib/control/tap.toml"

[[connection]]
from = "value/range-done"
to = "process/when-done/data"

[[connection]]
from = "process/pilte/blocked"
to = "process/when-done/control"

[[connection]]
from = "process/when-done"
to = "output/done"

# re-open the input gates for another value to loop on
[[connection]]
from = "process/when-done"
to = "value/start-signal"

[[connection]]
from = "value/limit-store"
to = "output/max"