name = "fibonacci"

[[flow]]
alias = "fib"
source="fib.toml"

[[function]]
alias = "print"
source = "lib://flowstdlib/stdio/stdout.toml"

[[connection]]
from = "flow/fib/series"
to = "function/print/stdout"