flow = "fibonacci"
version = "0.7.0"
author_name = "Andrew Mackenzie"
author_email = "andrew@mackenzie-serres.net"

[[process]]
alias = "fib"
source="fib.toml"

[[process]]
alias = "to_string"
source = "lib://flowstdlib/fmt/to_string.toml"

[[process]]
alias = "print"
source = "lib://runtime/stdio/stdout.toml"

[[connection]]
from = "process/fib/series"
to = "process/to_string"

[[connection]]
from = "process/to_string"
to = "process/print"