flow = "my-first-flow"
version = "0.11.0"
author_name = "Andrew Mackenzie"
author_email = "andrew@mackenzie-serres.net"

[[process]]
alias = "add"
source = "lib://flowstdlib/math/add"
input.i1 = { once =  0 }
input.i2 = { once =  1 }

[[connection]]
from = "add/sum"
to = "add/i2"

[[connection]]
from = "add/sum"
to = "stdout"

[[connection]]
from = "add/i2"
to = "add/i1"

[[process]]
source = "lib://flowruntime/stdio/stdout"