name = "fibonacci"

[[value]]
name = "HEAD-1"
type = "String"
value = "1"

[[value]]
name = "HEAD"
type = "String"
value = "1"

[[function]]
alias = "print"
source = "stdout.toml"

[[function]]
alias = "sum"
source = "add.toml"

[[connection]]
from = "value/HEAD-1"
to = "function/print/stdout"

[[connection]]
from = "value/HEAD-1"
to = "function/sum/i1"

[[connection]]
from = "value/HEAD"
to = "value/HEAD-1"

[[connection]]
from = "value/HEAD"
to = "function/sum/i2"

[[connection]]
from = "function/sum/o1"
to = "value/HEAD"