name = "fibonacci"

[[flow]]
alias = "fib"
source="fib.toml"

[[function]]
alias = "to_string"
source = "lib://flowstdlib/fmt/to_string.toml"

[[function]]
alias = "print"
source = "lib://flowstdlib/stdio/stdout.toml"

[[connection]]
from = "flow/fib/series"
to = "function/to_string"

[[connection]]
from = "function/to_string"
to = "function/print"