name = "fibonacci"

[[flow]]
alias = "fib"
source="fib.toml"

[[function]]
alias = "toString"
source = "lib://flowstdlib/fmt/toString.toml"

[[connection]]
from = "flow/fib/series"
to = "function/toString/in"

[[function]]
alias = "print"
source = "lib://flowstdlib/stdio/stdout.toml"

[[connection]]
from = "function/toString"
to = "function/print/stdout"