flow = "fibonacci"
version = "0.8.0"
author_name = "Andrew Mackenzie"
author_email = "andrew@mackenzie-serres.net"

[[process]]
alias = "fib"
source="fib"

[[process]]
alias = "to_string"
source = "lib://flowstdlib/fmt/to_string"

[[process]]
alias = "print"
source = "lib://flowruntime/stdio/stdout"

[[connection]]
from = "process/fib/series"
to = "process/to_string"

[[connection]]
from = "process/to_string"
to = "process/print"