flow = "fibonacci"
version = "0.8.0"
author_name = "Andrew Mackenzie"
author_email = "andrew@mackenzie-serres.net"

[[process]]
alias = "fib"
source="fib"

[[process]]
alias = "print"
source = "lib://flowruntime/stdio/stdout"

[[connection]]
from = "fib/series"
to = "print"