flow = "fib"

[[output]]
name = "series"
type = "Number"

[[process]]
alias = "buffer"
source = "lib://flowstdlib/data/buffer"

[[process]]
alias = "add"
source = "lib://flowstdlib/math/add"
input.i1 = { once = 0 }
input.i2 = { once = 1 }

[[connection]]
from = "add/sum"
to = "buffer"

[[connection]]
from = "add/sum"
to = "output/series"

[[connection]]
from = "buffer"
to = "add/i2"

[[connection]]
from = "add/i2"
to = "add/i1"

