flow = "fib"

[[process]]
alias = "HEAD-1"
source = "lib://flowstdlib/data/buffer"
input.default = {once = 1}

[[process]]
alias = "HEAD"
source = "lib://flowstdlib/data/buffer"
input.default = {once = 1}

[[process]]
alias = "sum"
source = "lib://flowstdlib/math/add"

[[output]]
name = "series"
type = "Number"

[[connection]]
from = "process/HEAD-1"
to = "process/sum/i1"

[[connection]]
from = "process/HEAD"
to = "process/HEAD-1"

[[connection]]
from = "process/HEAD"
to = "process/sum/i2"

[[connection]]
from = "process/sum"
to = "process/HEAD"

[[connection]]
from = "process/HEAD-1"
to = "output/series"