flow = "fib"

[[value]]
name = "HEAD-1"
type = "Number"
init = 1

[[value]]
name = "HEAD"
type = "Number"
init = 1

[[process]]
alias = "sum"
source = "lib://flowstdlib/math/add.toml"

[[output]]
name = "series"
type = "Number"

[[connection]]
from = "value/HEAD-1"
to = "process/sum/i1"

[[connection]]
from = "value/HEAD"
to = "value/HEAD-1"

[[connection]]
from = "value/HEAD"
to = "process/sum/i2"

[[connection]]
from = "process/sum"
to = "value/HEAD"

[[connection]]
from = "value/HEAD-1"
to = "output/series"