flow = "fib"

[[output]]
name = "series"
type = "Number"

[[process]]
alias = "HEAD-1"
source = "lib://flowstdlib/data/buffer"
input.default = {once = 1}

[[process]]
alias = "HEAD"
source = "lib://flowstdlib/data/buffer"
input.default = {once = 1}

[[process]]
alias = "sum"
source = "lib://flowstdlib/math/add"

[[connection]]
from = "HEAD-1"
to = "sum/i1"

[[connection]]
from = "HEAD"
to = "HEAD-1"

[[connection]]
from = "HEAD"
to = "sum/i2"

[[connection]]
from = "sum"
to = "HEAD"

[[connection]]
from = "HEAD-1"
to = "output/series"