[package]
name = "mandlebrot"
version = "0.0.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]

[lib]
name = "mandlebrot"
path = "lib.rs"

[dependencies]
flowrlib = { path = "../../flowrlib", version = "~0.4.1" }
serde_json = "1.0"
num = "0.1.27"

[workspace]
exclude = [".."]
