name = "mandlebrot"

[[function]]
alias = "args"
source = "lib://flowstdlib/env/args.toml"

[[function]]
alias = "write_bitmap"
source = "lib://flowstdlib/img/write_bitmap.toml"

[[connection]]
from = "function/args/0"
to = "function/write_bitmap/filename"