name = "mandlebrot"

[[function]]
alias = "args"
source = "lib://flowstdlib/env/args.toml"

[[function]]
alias = "write_bitmap"
source = "lib://flowstdlib/img/write_bitmap.toml"

[[connection]]
from = "function/args/1"
to = "function/write_bitmap/filename"

# Bounds
[[value]]
name = "bounds_separator"
type = "String"
constant = "x"

[[function]]
alias = "parse_bounds"
source = "src/parse_pair.toml"

[[connection]]
from = "function/args/2"
to = "function/parse_bounds/input"

[[connection]]
from = "value/bounds_separator"
to = "function/parse_bounds/separator"


# Points Separator
[[value]]
name = "point_separator"
type = "String"
constant = ","


# Upper Left Coordinate
[[function]]
alias = "parse_upper_left"
source = "src/parse_pair.toml"

[[connection]]
from = "value/point_separator"
to = "function/parse_upper_left/separator"

[[connection]]
from = "function/args/3"
to = "function/parse_upper_left/input"


# Lower Right Coordinate
[[function]]
alias = "parse_lower_right"
source = "src/parse_pair.toml"

[[connection]]
from = "value/point_separator"
to = "function/parse_lower_right/separator"

[[connection]]
from = "function/args/4"
to = "function/parse_lower_right/input"


