flow = "mandlebrot"

# Args
[[process]]
alias = "args"
source = "lib://flowr/args/get.toml"


# Bounds
[[process]]
alias = "parse_bounds"
source = "src/parse_pair.toml"

[[value]]
name = "bounds_separator"
type = "String"
init = "x"
static = true

[[connection]]
from = "process/args/2"
to = "process/parse_bounds/input"

[[connection]]
from = "value/bounds_separator"
to = "process/parse_bounds/separator"

#

# Points Separator
[[value]]
name = "point_separator"
type = "String"
init = ","
static = true


# Upper Left Coordinate
[[process]]
alias = "parse_upper_left"
source = "src/parse_pair.toml"

[[connection]]
from = "value/point_separator"
to = "process/parse_upper_left/separator"

[[connection]]
from = "process/args/3"
to = "process/parse_upper_left/input"

#

# Lower Right Coordinate
[[process]]
alias = "parse_lower_right"
source = "src/parse_pair.toml"

[[connection]]
from = "value/point_separator"
to = "process/parse_lower_right/separator"

[[connection]]
from = "process/args/4"
to = "process/parse_lower_right/input"


# Subflow 'render'
[[process]]
alias = "render"
source = "render.toml"

[[connection]]
from = "process/parse_bounds"
to = "process/render/bounds"

[[connection]]
from = "process/parse_upper_left"
to = "process/render/upper_left"

[[connection]]
from = "process/parse_lower_right"
to = "process/render/lower_right"

#

# Format Bitmap
#[[process]]
#alias = "format_bitmap"
#source = "lib://flowstdlib/img/format_png.toml"

#[[connection]]
#from = "process/render/bitmap_bounds"
#to = "process/format_bitmap/bounds"

#[[connection]]
#from = "process/render/bytes"
#to = "process/format_bitmap/bytes"


# Write Bitmap to a file
#[[process]]
#alias = "write_file"
#source = "lib://flowr/file/file_write.toml"

#[[connection]]
#from = "process/args/0"
#to = "process/write_file/filename"

#[[connection]]
#from = "process/format_bitmap"
#to = "process/write_file/bytes"
