flow = "mandlebrot"

# Args
[[process]]
alias = "args"
source = "lib://flowruntime/args/get"


# Bounds
[[process]]
alias = "parse_bounds"
source = "src/parse_pair/parse_pair"

[[process]]
alias = "bounds_separator"
source = "lib://flowstdlib/data/buffer/buffer"
input.default = {constant = "x"}

[[connection]]
from = "process/args/2"
to = "process/parse_bounds/input"

[[connection]]
from = "process/bounds_separator"
to = "process/parse_bounds/separator"

#

# Points Separator
[[process]]
alias = "point_separator"
source = "lib://flowstdlib/data/buffer/buffer"
input.default = {constant = ","}

# Upper Left Coordinate
[[process]]
alias = "parse_upper_left"
source = "src/parse_pair/parse_pair"

[[connection]]
from = "process/point_separator"
to = "process/parse_upper_left/separator"

[[connection]]
from = "process/args/3"
to = "process/parse_upper_left/input"

#

# Lower Right Coordinate
[[process]]
alias = "parse_lower_right"
source = "src/parse_pair/parse_pair"

[[connection]]
from = "process/point_separator"
to = "process/parse_lower_right/separator"

[[connection]]
from = "process/args/4"
to = "process/parse_lower_right/input"


# Subflow 'render'
[[process]]
alias = "render"
source = "render"

[[connection]]
from = "process/parse_bounds"
to = "process/render/bounds"

[[connection]]
from = "process/parse_upper_left"
to = "process/render/upper_left"

[[connection]]
from = "process/parse_lower_right"
to = "process/render/lower_right"

#

# Format Bitmap
#[[process]]
#alias = "format_bitmap"
#source = "lib://flowstdlib/img/format_png"

#[[connection]]
#from = "process/render/bitmap_bounds"
#to = "process/format_bitmap/bounds"

#[[connection]]
#from = "process/render/bytes"
#to = "process/format_bitmap/bytes"


# Write Bitmap to a file
#[[process]]
#alias = "write_file"
#source = "lib://flowruntime/file/file_write"

#[[connection]]
#from = "process/args/0"
#to = "process/write_file/filename"

#[[connection]]
#from = "process/format_bitmap"
#to = "process/write_file/bytes"
