name = "mandlebrot"

[[function]]
alias = "args"
source = "lib://flowstdlib/env/args.toml"

[[function]]
alias = "to_string"
source = "lib://flowstdlib/fmt/to_string.toml"

[[connection]]
from = "function/args/0"
to = "function/to_string"

[[connection]]
from = "function/args/1"
to = "function/to_string"

[[connection]]
from = "function/args/2"
to = "function/to_string"

[[function]]
alias = "print"
source = "lib://flowstdlib/stdio/stdout.toml"

[[connection]]
from = "function/to_string"
to = "function/print"