flow = "mandlebrot"

[[process]]
source = "parse_args"

[[process]]
source = "generate_pixels"

[[connection]]
from = "parse_args/size"
to = "generate_pixels/size"

#### Debug
[[process]]
source = "lib://flowruntime/stdio/stdout"

#[[connection]]
#from = "parse_args/filename"
#to = "stdout"

[[connection]]
from = "parse_args/size"
to = "stdout"

#[[connection]]
#from = "parse_args/bounds"
#to = "stdout"

[[connection]]
from = "generate_pixels/pixels"
to = "stdout"

