flow = "render"

[[input]]
name = "bounds"

[[input]]
name = "upper_left"

[[input]]
name = "lower_right"

[[output]]
name = "bytes"

[[output]]
name = "bounds"

[[connection]]
from = "input/bounds"
to = "output/bounds"