flow = "competing inputs"

[[process]]
alias = "one"
source = "lib://flowstdlib/data/buffer.toml"
input.default = {once = 1}

[[process]]
alias = "two"
source = "lib://flowstdlib/data/buffer.toml"
input.default = {once = 2}

[[process]]
alias = "sum"
source = "lib://flowstdlib/math/add.toml"

[[connection]]
from = "process/one"
to = "process/sum/i1"

[[connection]]
from = "process/two"
to = "process/sum/i1"