name = "competing inputs"

[[value]]
name = "one"
type = "Number"
init = 1
static = true

[[value]]
name = "two"
type = "Number"
init = 2
static = true

[[function]]
alias = "sum"
source = "lib://flowstdlib/math/add.toml"

[[connection]]
from = "value/one"
to = "function/sum/i1"

[[connection]]
from = "value/two"
to = "function/sum/i1"