flow = "dead-value-and-connected_value"

[[value]]
name = "source-value"
type = "String"
static = true

[[value]]
name = "dead-value"
type = "String"
static = true

[[connection]]
from = "value/source-value"
to = "value/dead-value"