flow = "echo inputs"

[[process]]
alias = "stdin"
source = "lib://flowrlib/stdio/stdin.toml"

[[process]]
alias = "print"
source = "lib://flowrlib/stdio/stdout.toml"

[[connection]]
name = "echo"
from = "process/stdin"
to = "process/print"