# This flow produces an infinite series of "2" on stdout.
# I considered a compiler check to not allow this, but it could be a valid scenario either as a standalone flow
# or as part of a bigger flow - so I didn't implement that and no test exists for it.

flow = "runaway"

[[value]]
name = "store"
type = "Number"
init = 2
static = true

[[process]]
alias = "print"
source = "lib://flowr/stdio/stdout.toml"

[[connection]]
from = "value/store"
to = "process/print"