[package]
name = "flowr"
version = "0.11.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
description = "A runner for compiled 'flow' programs"
license = "MIT"
documentation = "https://github.com/andrewdavidmackenzie/flow/README.md"
homepage = "http://andrewdavidmackenzie.github.io/flow/"
repository = "https://github.com/andrewdavidmackenzie/flow/"
readme = "README.md"
edition = "2018"

[[bin]]
name = "flowr"
path = "src/main.rs"

[features]
default = ["debugger", "native", "metrics"]
debugger = []
native = []
metrics = []

[dependencies.flowrlib]
path = "../flowrlib"
features = ["debugger", "metrics", "checks"]

[dependencies]
flow_impl = "=0.10.0"
provider = {path = "../provider"}
flowrstructs = {path = "../flowrstructs"}
clap = "~2"
simplog = "~1.2"
log = "0.4.6"
url = "~2.1"
serde_derive = "~1.0.27"
serde = "~1.0.27"
serde_json = "1.0"
num_cpus = "~1.10"
error-chain = "0.12.2"
image = "=0.23.10"
ctrlc = "3.1.4"

[dev-dependencies]
tempdir = "~0.3.5"