[package]
name = "flowr"
version = "0.11.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
description = "A runner for compiled 'flow' programs"
license = "MIT"
documentation = "https://github.com/andrewdavidmackenzie/flow/README.md"
homepage = "http://andrewdavidmackenzie.github.io/flow/"
repository = "https://github.com/andrewdavidmackenzie/flow/"
readme = "README.md"
edition = "2018"

[[bin]]
name = "flowr"
path = "src/main.rs"

[lib]
name = "flowrlib"
path = "src/lib/lib.rs"

[features]
default = ["debugger", "native", "metrics", "checks", "single_process"]
debugger = [] # feature to add the debugger
native = []   # Load native implementations of functions in libraries when possible
metrics = []  # feature for tracking of metrics during execution
checks = []   # feature to perform extra checks during flow execution
single_process = [] # Limit to a single process
distributed = ["zmq"] # Allow distributed multi-process client and server operation

[dependencies.flowrstructs]
path = "../flowrstructs"
features = ["debugger"]

[dependencies]
flow_impl = "=0.10.0"
flowstdlib = {path = "../flowstdlib"}
provider = {path = "../provider"}
clap = "~2"
simplog = "~1.2"
log = "0.4.6"
url = "~2.1"
serde_derive = "~1.0.27"
serde = "~1.0.27"
serde_json = "1.0"
num_cpus = "~1.10"
error-chain = "0.12.2"
image = "=0.23.10"
ctrlc = "3.1.4"
multimap = "~0.8"
wasmi = "0.6.2"

# Optional dependencies
zmq = { version = "0.9.2", optional = true }

[dev-dependencies]
tempdir = "~0.3.5"