[package]
name = "flowr"
version = "0.40.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
description = "A runner for compiled 'flow' programs"
license = "MIT"
documentation = "https://github.com/andrewdavidmackenzie/flow/README.md"
homepage = "http://andrewdavidmackenzie.github.io/flow/"
repository = "https://github.com/andrewdavidmackenzie/flow/"
readme = "README.md"
edition = "2021"

[badges]
maintenance = { status = "actively-developed" }

[lib]
name = "flowrlib"
path = "src/lib/lib.rs"

[features]
default = ["debugger", "native", "metrics", "checks", "distributed", "wasmtime_runtime"]
#default = ["debugger", "native", "metrics", "checks", "wasmtime_runtime"]
debugger = ["flowcore/debugger", "rustyline"] # feature to add the debugger, requires flowcore crate to have feature enabled also
native = ["flowstdlib"]   # Load native implementations of functions in libraries when possible
metrics = []  # feature for tracking of metrics during execution
checks = []   # feature to perform extra checks during flow execution
distributed = ["zmq", "simpdiscover", "portpicker"] # Allow distributed multi-process client and server operation
online_tests = []
wasmi_runtime = ["wasmi"] # First WASM implementation
wasmtime_runtime = ["wasmtime", "anyhow"] # An alternative WASM implementation

[dependencies]
flowcore = {path = "../flowcore", version = "0.40.0"}

clap = "~2"
simplog = "~1.3"
log = "0.4.6"
simpath = { version = "~2.3", features = ["urls"]}
url = { version = "2.2", features = ["serde"] }
serde_derive = "~1.0.27"
serde = "~1.0.27"
serde_json = { version = "1.0", default-features = false }
num_cpus = "1.13.0"
error-chain = "0.12.2"
image = "=0.23.10"
multimap = "~0.8"
ctrlc = "3.1.9"

# Optional dependencies
simpdiscover = { version = "0.2.1", optional = true }
portpicker = { version = "0.1.1", optional = true }
wasmi = { version = "0.9.0", optional = true }
wasmtime = { version = "0.30.0", default-features = false, features = ["cranelift"], optional = true }
flowstdlib = {path = "../flowstdlib", version = "0.40.0", optional = true }
zmq = { version = "0.9.2", optional = true }
rustyline = {version = "9.0.0", optional = true }
anyhow = { version = "1.0", optional = true}

[dev-dependencies]
tempdir = "~0.3.5"
serial_test = "0.5.0"
