[package]
name = "flowrlib"
version = "0.2.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]

[lib]
name = "flowrlib"
path = "src/lib.rs"

test = true
doctest = true
bench = true
doc = true

[dependencies]
log = "0.3.8"