[package]
name = "flowrlib"
version = "0.1.1"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]

[lib]
name = "flowrlib"
path = "src/flowrlib.rs"

test = true
doctest = true
bench = true
doc = true

[dependencies]