[package]
name = "flowrlib"
version = "0.7.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
description = "The runtime library for executing 'flow' programs compiled with the 'flowc' compiler"
license = "MIT"

[lib]
name = "flowrlib"
path = "src/lib.rs"

test = true
doctest = true
bench = true
doc = true

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"

[features]
default = ["debugger", "metrics", "logging"]
metrics = []
debugger = []
logging = []

[dependencies]
multimap = { git = "https://github.com/andrewdavidmackenzie/multimap" }
log = "0.4.6"
serde_derive = "~1.0.27"
serde = "~1.0.27"
serde_json = "1.0"
wasmi = { git = "https://github.com/andrewdavidmackenzie/wasmi" }