[package]
name = "flowrlib"
version = "0.3.1"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
description = "The runtime library for executing 'flow' programs compiled with the 'flowc' compiler"
license = "MIT"

[lib]
name = "flowrlib"
path = "src/lib.rs"

test = true
doctest = true
bench = true
doc = true

[dependencies]
log = "0.3.8"