[package]
name = "divide"
version = "0.11.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
edition = "2018"

[lib]
name = "divide"
crate-type = ["cdylib"]
path = "divide.rs"

[profile.release]
debug = false
lto = true
opt-level = 's'

[dependencies]
flowcore = "=0.34.7"
flow_impl_derive = "=0.10.0"
serde_json = "1.0"

[workspace]
exclude = ["../../../"]
