function = "Compare"

[[input]]
name = "left"

[[input]]
name = "right"

[[output]]
name = "equal"
type = "Bool"

[[output]]
name = "lt"
type = "Bool"

[[output]]
name = "lte"
type = "Bool"

[[output]]
name = "gt"
type = "Bool"

[[output]]
name = "gte"
type = "Bool"