[package]
name = "web"
version = "0.1.0"
authors = ["Andrew Mackenzie"]
edition = "2018"
categories = ["wasm"]
description = "A web version of the 'flow' project for data driven parallel applications"
license = "Apache-2.0/MIT"
readme = "./README.md"
repository = "https://github.com/andrewdmackenzie/flow"

[lib]
crate-type = ["cdylib"]

[dependencies]
flowclib = { path = "../../flowclib", version = "~0.7.0" }
flowrlib = { path = "../../flowrlib", version = "~0.7.0" }
flowstdlib = { path = "../../flowstdlib", version = "~0.7.0" }
serde_json = "1.0"
wasm-bindgen = "0.2.25"
wasm-logger = "0.1.4"
log = {version = "0.4.6", features = ["std"]}
webprovider = { path = "../../webprovider", version = "0.1.0"}

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.5", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
wee_alloc = { version = "0.4.2", optional = true }

[features]
default = ["console_error_panic_hook"]

[dependencies.web-sys]
version = "0.3"
features = [
  "Document",
  "Element",
  'HtmlButtonElement',
  "HtmlElement",
  "Node",
  "Text",
  "Window",
  "console",
]