name = "flow2"

[[function]]
alias = "function6"
source = "function6.toml"

[[input]]
name = "i1"
type = "String"

[[input]]
name = "i2"
type = "String"

[[input]]
name = "i3"
type = "String"

[[input]]
name = "i4"
type = "String"

[[output]]
name = "o1"
type = "String"

[[output]]
name = "o2"
type = "String"

[[connection]]
from = "input/i1"
to = "function/function6/i1"

[[connection]]
from = "input/i2"
to = "function/function6/i2"

[[connection]]
from = "input/i3"
to = "function/function6/i3"

[[connection]]
from = "input/i4"
to = "function/function6/i4"

[[connection]]
from = "function/function6/o1"
to = "output/o1"

[[connection]]
from = "function/function6/o2"
to = "output/o2"