name = "function6"

[[input]]
name = "i1"
type = "String"

[[input]]
name = "i2"
type = "String"

[[input]]
name = "i3"
type = "String"

[[input]]
name = "i4"
type = "String"

[[output]]
name = "o1"
type = "String"

[[output]]
name = "o2"
type = "String"