name = "function6"

[[input]]
name = "i1"
datatype = "String"

[[input]]
name = "i2"
datatype = "String"

[[input]]
name = "i3"
datatype = "String"

[[input]]
name = "i4"
datatype = "String"

[[output]]
name = "o1"
datatype = "String"

[[output]]
name = "o2"
datatype = "String"