name = "hello-world-toml"

[[entity]]
name = "terminal"
source = "terminal.toml"

[[flow]]
name = "hello"
source = "flow1.toml"

[[connection]]
name = "message"
from = "flow/hello/out"
to = "entity/terminal/stdout"