name = "hello-world-toml-context"

[[function]]
name = "print"
source = "terminal.toml"

[[flow]]
name = "hello"
source = "flow1.toml"

[[connection]]
name = "message"
from = "flow/hello/out"
to = "function/terminal/stdout"