name = "hello-world-toml-flow1"

[[value]]
name = "message"
datatype = "String"
value = "Hello World!"

[[output]]
name = "out"
datatype = "String"

[[connection]]
name = "message"
from = "value/message"
to = "flow/this/out"