name = "say hello"

[[value]]
name = "message"
datatype = "String"
value = "Hello World!"

[[io]]
name = "out"
datatype = "String"

[[connection]]
name = "message"
from = "value/message"
to = "flow/this/out"