[package]
name = "flowide"
version = "0.1.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
edition = "2018"

[[bin]]
name = "flowide"
path = "src/main.rs"

[dependencies]
flowclib = {path = "../flowclib"}
flowrlib = {path = "../flowrlib"}
flow_impl = "=0.8.3"
toml = "0.4"
url = "~2.1"
serde_json = "1.0"
runtime = { path = "../runtime" }
provider = { path = "../provider" }
flowstdlib = { path = "../flowstdlib", features = [ "native" ] }
log = "0.4.6"
gtk-fnonce-on-eventloop = {git = "https://github.com/andrewdavidmackenzie/gtk-rs-state" }
lazy_static = "*"

gdk-pixbuf = "0.8.0"

[dependencies.gtk]
version = "0.8.0"
features = ["v3_24"]

[dependencies.gio]
version = "0.8.0"
features = ["v2_44"]