[package]
name = "flowide"
version = "0.1.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
edition = "2018"

[[bin]]
name = "flowide"
path = "src/main.rs"

[dependencies]
flow_impl = "=0.8.5"
flowrlib = "=0.8.8"
flowruntime = { path = "../flowruntime"}
flowstdlib = { path = "../flowstdlib", features = [ "native" ] }
flowclib = { path = "../flowclib" }
provider = { path = "../provider" }

toml = "0.4"
url = "~2.1"
serde_json = "1.0"
log = "0.4.6"
lazy_static = "1"
gtk-rs-state = "0.3"
cairo-rs = "0.8"
gdk = "0.12"
gdk-pixbuf = "0.8"
gio = "0.8"
glib = "0.9"
gtk = "0.8"
pango = "0.8"