[package]
name = "format_png"
version = "0.11.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
edition = "2018"

[lib]
name = "format_png"
crate-type = ["cdylib"]
path = "format_png.rs"

[profile.release]
debug = false
lto = true
opt-level = 's'

[dependencies]
flowcore = "=0.34.7"
flow_impl_derive = "=0.10.0"
serde_json = "1.0"
image = "=0.23.10"

[workspace]
exclude = ["../../../"]
