function = "format_png"
implementation = "format_png.rs"

[[input]]
name = "bytes" # - the bytes to encode as a bitmap

[[input]]
name = "bounds" # - Json with width and depth of the image the bytes represent
type = "Value"

[[output]]
type = "Array" # - The bytes representing the PNG encoding of the image, as a String