flow = "composites"

[[input]]
name = "limit"
type = "number"

[[output]]
name = "composites"
type = "number"

# Generate a set of divisors from 2 .. SQRT(limit)
[[process]]
alias = "sqrt"
source = "lib://flowstdlib/math/sqrt"

[[connection]]
from = "input/limit"
to = "sqrt"

[[process]]
alias = "divisors"
source = "lib://flowstdlib/math/sequence"
input.start = {once =  2}
input.step = {once =  1}

[[connection]]
from = "sqrt"
to = "divisors/end"

[[process]]
source = "generate_composites"

[[connection]]
from = "divisors/sequence"
to = "generate_composites/start"

[[connection]]
from = "input/limit"
to = "generate_composites/limit"

[[connection]]
from = "generate_composites/composites"
to = "output/composites"