flow = "generate_composites"

[[input]]
name = "start"
type = "number"

[[input]]
name = "limit"
type = "number"

[[output]]
name = "composites"
type = "number"

# start each sequence at 2 x input/start - no point in generating composites from the divisor itself
# e.g. if start = 2, first composite will be 4
[[connection]]
from = "input/start"
to = "multiply/i1"
[[process]]
alias = "multiply"
source = "lib://flowstdlib/math/multiply"
input.i2 = {always =  2}
[[connection]]
from = "multiply"
to = "composite-sequence/start"

[[process]]
alias = "composite-sequence"
source = "lib://flowstdlib/math/sequence"

# buffer the limit so it can be reused each time
[[connection]]
from = "input/limit"
to = "limit-buffer"
[[process]]
alias = "limit-buffer"
source = "lib://flowstdlib/data/buffer"
[[connection]]
from = "limit-buffer"
to = "limit-buffer"

[[connection]]
from = "limit-buffer"
to = "composite-sequence/limit"

# Advance to the next composite in the series by adding the divisor
# e.g. if start = 2, first composite will be 4, add 2 to get next one, 6, then 8 etc
[[connection]]
from = "input/start"
to = "composite-sequence/step"

[[connection]]
from = "composite-sequence/sequence"
to = "output/composites"