flow = "prime"
docs = "DESCRIPTION.md"

# Read the limit from the command line
[[process]]
alias = "args"
source = "context://args/get"

[[connection]]
from = "args/json/1"
to = "candidates/end"

####### All numbers - Sequence
# Generate the sequence of numbers from 1..limit of possible primes
[[process]]
alias = "candidates"
source = "lib://flowstdlib/math/sequence"
input.start = {once =  1}
input.step = {once =  1}

######### All numbers - gather into an array
[[process]]
alias = "all-numbers"
source = "lib://flowstdlib/data/accumulate"
input.partial = {once =  []}

[[connection]]
from = "candidates/sequence"
to = "all-numbers/values"

[[connection]]
from = "args/json/1"
to = "all-numbers/chunk_size"

[[connection]] # loop-back
from = "all-numbers/chunk_size"
to = "all-numbers/chunk_size"

[[connection]]
from = "all-numbers/partial"
to = "all-numbers/partial"

####### Composites
[[process]]
alias = "composites"
source = "composites"

[[connection]]
from = "args/json/1"
to = "composites/limit"

####### Remove composites from entire list
[[process]]
alias = "remove"
source = "lib://flowstdlib/data/remove"

[[connection]]
from = "all-numbers/chunk"
to = "remove/array"

[[connection]]
from = "composites/composites"
to = "remove/value"

[[connection]] # loopback
from = "remove"
to = "remove/array"

[[connection]]
from = "remove"
to = "print"

####### Output
[[process]]
alias = "print"
source = "context://stdio/stdout"

