[package]
name = "provider"
version = "0.4.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
description = "A content provider for 'flow' tools"
license = "MIT"
documentation = "https://github.com/andrewdavidmackenzie/flow/README.md"
homepage = "https://github.com/andrewdavidmackenzie/flow/README.md"
repository = "https://github.com/andrewdavidmackenzie/flow/"
readme = "https://github.com/andrewdavidmackenzie/flow/README.md"

[dependencies]
flowrlib = { path = "../flowrlib", version = "~0.7.0" }
log = "0.3.8"
url = "~1.6.0"
tempdir = "~0.3.5"
curl = "~0.4.11"
simpath = "~1.2"
glob = "~0.2.11"