[package]
name = "select"
version = "0.11.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
edition = "2018"

[lib]
name = "select"
crate-type = ["cdylib"]
path = "select.rs"

[profile.release]
debug = false
lto = true
codegen-units = 1
opt-level = 's' # Optimize for size
panic = 'abort' # About unwinding code

[dependencies]
flowcore = "0.42"
flowmacro = "0.42"
serde_json = "1.0"

[workspace]
exclude = ["../../.."]
