function = "tap"
source = "tap.rs"
docs = "tap.md"
build_script = "Cargo.toml"

[[input]]
name = "data" # - the data flow we wish to control the flow if
type = "Value"

[[input]]
name = "control" # - a boolean value to determine in `data` is passed on or not
type = "Bool"

[[output]]
type = "Value" # `data` is output if `control` is true, nothing if `control` is false