[book]
title = "The `flow` Guide"
authors = ["Andrew Mackenzie"]
description = "A guide to what 'flow' is and how to use it"
multilingual = false
src = "guide"

[build]
build-dir = "guide.build"
create-missing = false

[output.html]

[output.linkcheck]  # enable the "mdbook-linkcheck" renderer