flow = "range"

[[process]]
alias = "args"
source = "lib://flowruntime/args/get"

[[connection]]
from = "process/args/1"
to = "process/to_number"

[[process]]
alias = "to_number"
source = "lib://flowstdlib/fmt/to_number"

[[connection]]
from = "process/to_number"
to = "process/sequence/end"

[[process]]
alias = "sequence"
source = "lib://flowstdlib/math/sequence"
input.start = {once = 1}

[[connection]]
from = "process/sequence/sequence"
to = "process/print"

# Output a string to show we're done when the series ends
[[process]]
alias = "tap"
source = "lib://flowstdlib/control/tap"
input.data = {constant = "Range done"}

[[connection]]
from = "process/sequence/done"
to = "process/tap/control"

[[connection]]
from = "process/tap"
to = "process/print"

# Output
[[process]]
alias = "print"
source = "lib://flowruntime/stdio/stdout"