flow = "range"

[[process]]
alias = "args"
source = "lib://flowruntime/args/get"

[[connection]]
from = "args/1"
to = "to_number"

[[process]]
alias = "to_number"
source = "lib://flowstdlib/fmt/to_number"

[[connection]]
from = "to_number"
to = "sequence/end"

[[process]]
alias = "sequence"
source = "lib://flowstdlib/math/sequence"
input.start = {Once =  1}
input.step = {Once =  1}

[[connection]]
from = "sequence/sequence"
to = "print"

# Output a string to show we're done when the series ends
[[process]]
alias = "join"
source = "lib://flowstdlib/control/join"
input.data = {Once =  "Range done"}

[[connection]]
from = "sequence/last"
to = "join/control"

[[connection]]
from = "join"
to = "print"

# Output
[[process]]
alias = "print"
source = "lib://flowruntime/stdio/stdout"