[[value]]
name = "start"
type = "Number"
init = 1

[[connection]]
from = "value/start"
to = "flow/range/start"

[[function]]
alias = "args"
source = "lib://flowstdlib/env/args.toml"

[[connection]]
from = "function/args/1"
to = "function/to_number"

[[function]]
alias = "to_number"
source = "lib://flowstdlib/fmt/to_number.toml"

[[connection]]
from = "function/to_number"
to = "flow/range/limit"

[[flow]]
alias = "range"
source = "range.toml"

[[function]]
alias = "to_string"
source = "lib://flowstdlib/fmt/to_string.toml"

[[connection]]
from = "flow/range/series"
to = "function/to_string"

[[function]]
alias = "print"
source = "lib://flowstdlib/stdio/stdout.toml"

[[connection]]
from = "function/to_string"
to = "function/print"