flow = "range"

[[process]]
alias = "args"
source = "lib://flowr/args/get.toml"

[[connection]]
from = "process/args/1"
to = "process/to_number"

[[process]]
alias = "to_number"
source = "lib://flowstdlib/fmt/to_number.toml"

[[connection]]
from = "process/to_number"
to = "process/sequence/end"

[[process]]
alias = "sequence"
source = "lib://flowstdlib/math/sequence.toml"
input.start = {once = 1}

[[process]]
alias = "to_string"
source = "lib://flowstdlib/fmt/to_string.toml"

[[connection]]
from = "process/sequence/sequence"
to = "process/to_string"

# Output a string to show we're done when the series ends
[[process]]
alias = "tap"
source = "lib://flowstdlib/control/tap.toml"
input.data = {once = "Range done"}

[[connection]]
from = "process/sequence/done"
to = "process/tap/control"

[[connection]]
from = "process/tap"
to = "process/print"

# Output
[[process]]
alias = "print"
source = "lib://flowr/stdio/stdout.toml"

[[connection]]
from = "process/to_string"
to = "process/print"