name = "range"

[[input]]
name = "start"
type = "Number"

[[input]]
name = "limit"
type = "Number"

[[output]]
name = "series"
type = "Number"

[[output]]
name = "min"
type = "Number"

[[output]]
name = "max"
type = "Number"

[[flow]]
alias = "pilt"
source = "pass_if_less_than.toml"

[[function]]
alias = "add"
source = "lib://flowstdlib/math/add.toml"

[[connection]]
from = "input/start"
to = "flow/pilt/in"

# A store for the limit value that always refreshes itself, so it's value is always available
[[value]]
name = "limit_store"
type = "Number"

[[connection]]
from = "input/limit"
to = "value/limit_store"

# TODO ADM need the persistent store
#[[connection]]
#from = "value/limit_store"
#to = "value/limit_store"

[[connection]]
from = "value/limit_store"
to = "flow/pilt/max"


[[connection]]
from = "flow/pilt/out"
to = "output/series"

[[connection]]
from = "flow/pilt/out"
to = "function/add/i1"

[[value]]
name = "one"
type = "Number"
constant = 1

[[connection]]
from = "value/one"
to = "function/add/i2"

[[connection]]
from = "function/add"
to = "flow/pilt/in"

[[connection]]
from = "input/start"
to = "output/min"

[[connection]]
from = "input/limit"
to = "output/max"