function = "pixel_to_point"
source = "pixel_to_point.rs"

[[input]]
name = "bounds"
type = "Array/Array/Number"

[[input]]
name = "pixel"
type = "Array/Number"

[[input]]
name = "size"
type = "Array/Number"

# Pixel and point are output together
[[output]]
type = "Value"