function = "compare"
source = "compare.rs"
docs = "compare.md"
type = "rust"

[[input]]
name = "left" # - left hand input
type = "number"

[[input]]
name = "right" # - right hand input
type = "number"

[[output]]
name = "equal" # - `equal` \[Boolean\] - outputs true if the two values are equal
type = "Bool"

[[output]]
name = "lt" # - `lt` \[Boolean\] - outputs true if the left hand value is less than the right hand value
type = "Bool"

[[output]]
name = "lte" # - `lte` \[Boolean\] - outputs true if the left hand value is less than or equal to the right hand value
type = "Bool"

[[output]]
name = "gt" # - `gt` \[Boolean\] - outputs true if the left hand value is greater than the right hand value
type = "Bool"

[[output]]
name = "gte" # - `gte` \[Boolean\] - outputs true if the left hand value is greater than or equal to the right hand value
type = "Bool"