[package]
name = "flowui"
version = "0.1.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]

[dependencies]
# TODO Play with web platform
#itertools = "*"
#webplatform = "*"

flowlib = { path = "../rust/lib" }