flow = "arrays"
version = "0.1.0"
author_name = "Andrew Mackenzie"
author_email = "andrew@mackenzie-serres.net"

[[process]]
alias = "sequence"
source = "lib://flowstdlib/math/sequence"
input.start = {Once =  1}
input.end = {Once =  20}
input.step = {Once =  1}

[[connection]]
from = "sequence/sequence"
to = "accumulator/values"

[[process]]
alias = "accumulator"
source = "lib://flowstdlib/data/accumulate"
input.partial = {Once =  []}
input.chunk_size = {Always =  4}

[[connection]]
from = "accumulator/partial"
to = "accumulator/partial"

[[connection]]
from = "accumulator/chunk"
to = "add/i1"

[[process]]
alias = "add"
source = "lib://flowstdlib/math/add"
input.i2 = {Always =  1}

[[connection]]
from = "add/sum"
to = "print"

[[process]]
alias = "print"
source = "lib://flowruntime/stdio/stdout"