flow = "arrays"
version = "0.1.0"
author_name = "Andrew Mackenzie"
author_email = "andrew@mackenzie-serres.net"

[[process]]
alias = "sequence"
source = "lib://flowstdlib/math/sequence"
input.start = {once = 1}
input.end = {once = 20}
input.step = {once = 1}

[[connection]]
from = "process/sequence/sequence"
to = "process/accumulator/values"

[[process]]
alias = "accumulator"
source = "lib://flowstdlib/data/accumulate"
input.partial = {once = []}
input.chunk_size = {constant = 4}

[[connection]]
from = "process/accumulator/partial"
to = "process/accumulator/partial"

[[connection]]
from = "process/accumulator/chunk"
to = "process/adder/i1"

[[process]]
alias = "adder"
source = "lib://flowstdlib/math/add"
input.i2 = {constant = 1}

[[connection]]
from = "process/adder"
to = "process/print"

[[process]]
alias = "print"
source = "lib://flowruntime/stdio/stdout"