flow = "arrays"
version = "0.1.0"
author_name = "Andrew Mackenzie"
author_email = "andrew@mackenzie-serres.net"

[[process]]
alias = "p1"
source = "lib://flowstdlib/math/sequence"
input.start = {once = 1}
input.end = {once = 20}

[[connection]]
from = "process/p1/sequence"
to = "process/p2"

[[process]]
alias = "p2"
source = "lib://flowstdlib/data/compose_array"

[[connection]]
from = "process/p2"
to = "process/p3/i1"

[[process]]
alias = "p3"
source = "lib://flowstdlib/math/add"
input.i2 = {constant = 1}

[[connection]]
from = "process/p3"
to = "process/p4"

[[process]]
alias = "p4"
source = "lib://runtime/stdio/stdout"