flow = "pipeline"
version = "0.1.0"
author_name = "Andrew Mackenzie"
author_email = "andrew@mackenzie-serres.net"

[[process]]
alias = "range"
source = "lib://flowstdlib/math/sequence"
input.start = {once = 1}
input.end = {once = 20}
input.step = {once = 1}

[[connection]]
from = "process/range/sequence"
to = "process/add1/i1"

[[process]]
alias = "add1"
source = "lib://flowstdlib/math/add"
input.i2 = {constant = 1}

[[connection]]
from = "process/add1"
to = "process/divide2/dividend"

[[process]]
alias = "divide2"
source = "lib://flowstdlib/math/divide"
input.divisor = {constant = 2}

[[connection]]
from = "process/divide2/result"
to = "process/add2/i1"

[[process]]
alias = "add2"
source = "lib://flowstdlib/math/add"
input.i2 = {constant = 2}

[[connection]]
from = "process/add2"
to = "process/divide4/dividend"

[[process]]
alias = "divide4"
source = "lib://flowstdlib/math/divide"
input.divisor = {constant = 2}

[[connection]]
from = "process/divide4/result"
to = "process/print"

[[process]]
alias = "print"
source = "lib://flowruntime/stdio/stdout"