flow = "pipeline"
version = "0.1.0"
author_name = "Andrew Mackenzie"
author_email = "andrew@mackenzie-serres.net"

[[process]]
alias = "range"
source = "lib://flowstdlib/math/sequence"
input.start = {Once =  1}
input.end = {Once =  20}
input.step = {Once =  1}

[[connection]]
from = "range/sequence"
to = "add1/i1"

[[process]]
alias = "add1"
source = "lib://flowstdlib/math/add"
input.i2 = {Always =  1}

[[connection]]
from = "add1/sum"
to = "divide2/dividend"

[[process]]
alias = "divide2"
source = "lib://flowstdlib/math/divide"
input.divisor = {Always =  2}

[[connection]]
from = "divide2/result"
to = "add2/i1"

[[process]]
alias = "add2"
source = "lib://flowstdlib/math/add"
input.i2 = {Always =  2}

[[connection]]
from = "add2/sum"
to = "divide4/dividend"

[[process]]
alias = "divide4"
source = "lib://flowstdlib/math/divide"
input.divisor = {Always =  2}

[[connection]]
from = "divide4/result"
to = "print"

[[process]]
alias = "print"
source = "lib://flowruntime/stdio/stdout"