[package]
name = "render_pixel"
version = "0.11.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
edition = "2018"

[lib]
name = "render_pixel"
crate-type = ["cdylib"]
path = "render_pixel.rs"

[profile.release]
debug = false
lto = true
opt-level = 's'

[dependencies]
flow_impl = "=0.10.0"
flow_impl_derive = "=0.10.0"
num = "0.3.0"
serde_json = "1.0"

[dev-dependencies]
wasm-bindgen-test = "0.3.0"

[workspace]
exclude = ["../../../"]
