name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule: # Build every day at 5PM UTC
    - cron: '0 17 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [ macos-latest, ubuntu-latest ]
#          rust: [ nightly ]

    steps:
    - uses: actions/checkout@v2

    - name: Cache Cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-stable-cargo-registry-cache-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-stable-cargo-registry-

    - name: SetupEnvVars
      run: echo "FLOW_LIB_PATH=$GITHUB_WORKSPACE,$GITHUB_WORKSPACE/flowr/src/lib" >> "$GITHUB_ENV"

#    - name: Install latest nightly
#      uses: actions-rs/toolchain@v1
#      with:
#        toolchain: nightly
#        override: true
#        components: clippy
    - name: MakeCoveragePossibleInStable
      run: echo RUSTC_BOOTSTRAP=1 >> "$GITHUB_ENV"

    - name: InstallLinuxDependencies
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get -y install libzmq3-dev binaryen

    - name: InstallMacDependencies
      if: matrix.os == 'macos-latest'
      run: brew install zmq binaryen

    - name: AddWasmTarget
      run: rustup target add wasm32-unknown-unknown

    - name: InstallWasmTools
      run: cargo install wasm-gc wasm-snip

    - name: Build-and-install-flowc
      run: cargo install --path flowc

    - name: Build-flowstdlib
      run: cargo build -p flowstdlib

    - name: Clippy
      run: |
        rustup component add clippy
        cargo clippy -- -D warnings

    - name: ConfigureCoverage
      if: matrix.os == 'ubuntu-latest'
      run: |
        cargo install grcov
        rustup component add llvm-tools-preview
        echo RUSTFLAGS="-Zinstrument-coverage" >> "$GITHUB_ENV"
        echo LLVM_PROFILE_FILE="flow-%p-%m.profraw" >> "$GITHUB_ENV"

    - name: Build
      run: cargo build

    - name: Run tests
      run: |
        RUST_LOG=trace cargo test --features "online_tests"
        cargo test -p flowstdlib

    - name: UploadCoverage
      if: matrix.os == 'ubuntu-latest'
      run: |
        grcov . --binary-path target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
        bash <(curl -s https://codecov.io/bash) -f lcov.info
        rm -f lcov.info

    - name: Docs
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get -y install graphviz
        cargo install mdbook
        cargo install mdbook-linkcheck
        make docs
        make trim-docs

    - name: DeployDocsToGHPages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      if: matrix.os == 'ubuntu-latest' && github.ref == 'refs/heads/master'
      with:
        branch: gh-pages
        folder: target/html