flow = "range-of-ranges"

# Generate a sequence of numbers 1 2 3 4 5 6 7 8 9
[[process]]
alias = "limit-sequence"
source = "lib://flowstdlib/math/sequence"
input.start = {once = 1}
input.end = {once = 9}

[[process]]
alias = "start-of-each"
source = "lib://flowstdlib/data/buffer"
input.default = {constant = 0}

[[connection]]
from = "process/start-of-each"
to = "process/sequence-of-sequences/start"

# Generate a sequence of numbers from 0 upto the value from sequence above
# 0 1
# 0 1 2
# .....
# 0 1 2 3 4 5 6 7 8 9
[[process]]
alias = "sequence-of-sequences"
source = "lib://flowstdlib/math/sequence"

# Connect the list of limits to use for each sequence to the generator of the sequence of sequences
[[connection]]
from = "process/limit-sequence/sequence"
to = "process/sequence-of-sequences/end"

# We will be printing out the sequence-of-sequences of numbers
[[process]]
alias = "print"
source = "lib://flowruntime/stdio/stdout"

# Connect the sequence-of-sequences to the print function
[[connection]]
from = "process/sequence-of-sequences/sequence"
to = "process/print"