flow = "range-of-ranges"

# Generate a sequence of numbers 1 2 3 4 5 6 7 8 9
[[process]]
alias = "limit-sequence"
source = "lib://flowstdlib/math/sequence"
input.start = {Once =  1}
input.end = {Once =  9}
input.step = {Once =  1}

[[process]] # a Buffer between the constant starting point of 0 and the 'start' input to avoid priority issues for the input
alias = "start-of-each"
source = "lib://flowstdlib/data/buffer"
input.default = {Always =  0}

[[connection]]
from = "start-of-each"
to = "sequence-of-sequences/start"

# Generate a sequence of numbers from 0 upto the value from sequence above
# 0 1
# 0 1 2
# .....
# 0 1 2 3 4 5 6 7 8 9
[[process]]
alias = "sequence-of-sequences"
source = "lib://flowstdlib/math/sequence"
input.step = {Once =  1}

# Connect the list of limits to use for each sequence to the generator of the sequence of sequences
[[connection]]
from = "limit-sequence/sequence"
to = "sequence-of-sequences/end"

# We will be printing out the sequence-of-sequences of numbers
[[process]]
alias = "print"
source = "lib://flowruntime/stdio/stdout"

# Connect the sequence-of-sequences to the print function
[[connection]]
from = "sequence-of-sequences/sequence"
to = "print"