name = "hello-world-simple-toml"

[[value]]
name = "message"
datatype = "String"
value = "Hello World!"

[[function]]
name = "print"
source = "terminal.toml"

[[connection]]
name = "message"
from = "value/message"
to = "function/print/stdout"